### ISSUE TITLE
less calculate bug

### ISSUE THREAD

**Issue by vopjie** [less/less.js#3118] opened 2017-10-19 07:25 UTC
NORMAL:
width: 43 + 20px;
=>
width: 63px;

BUG:
width: (43 + 20)px;
=>
width: 63 px;            // with a space

**Comment by seven-phases-max** [comment] 2017-11-06 18:01
Not a bug... Nothing in the documentation suggests you can add units to the result of an arithmetic expressions like this. String-based concatenation never works in Less that way. For Less  `px` in `(43 + 20)px` is a distinct abstract identifier (having nothing to do with any prior values/identifiers) and as any distinct identifier it's rendered with a space.

To add a unit to an expression use either unit function or a arithmetic op - e.g. see https://github.com/less/less.js/issues/1375#issuecomment-171446510

---
I can imagine how this may transform into major feature request like "Preserve CSS value formatting", but that should be quite strict and well-thought "big" proposal (counting all things like #1375 and all the problems mentioned there). So by now this behavior is expected/intended.

**Comment by seven-phases-max** [comment] 2017-11-06 18:02
Closing as expected behaviour.

**Closed by seven-phases-max** 2017-11-06 18:02 UTC
Labels: Bug

**Comment by vopjie** [comment] 2017-11-10 03:17
got  it, thanks
