### ISSUE TITLE
Class constructor FileManager cannot be invoked without 'new'.

### ISSUE THREAD

**Issue by micooz** [less/less.js#3414] opened 2019-08-17 04:24 UTC
It seems that **v3.10.0** breaks my build, webpack logs below:

```
ERROR in ./src/pages/score/components/current/no-join/index.less
Module build failed (from ./node_modules/_mini-css-extract-plugin@0.5.0@mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js):


Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)
    at runLoaders (/home/admin/build/node_modules/_webpack@4.39.2@webpack/lib/NormalModule.js:313:20)
    at /home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:367:11
    at /home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:111:13)
```

Everything is ok when downgrade to **v3.9.0**, please investigate this issue and hope to fix it as soon as possible.

**Comment by xiaoningzihai** [comment] 2019-08-17 05:40
I have the same problem，you mast change you 'package.json' => "less": "~3.9.0", limit version

**Comment by alexyan** [comment] 2019-08-17 05:49
+1

**Comment by AlwaysSkylll** [comment] 2019-08-17 05:57
+1

**Comment by lzf0402** [comment] 2019-08-17 05:58
+1!
急 ～

**Comment by Liqihan** [comment] 2019-08-17 06:03
+1

**Comment by yolo2013** [comment] 2019-08-17 06:17
same problem

**Comment by Doneitha** [comment] 2019-08-17 06:18
+1  version  less 3.9.0    less-loader 4.1.0

**Comment by Doneitha** [comment] 2019-08-17 06:26
可以把package.json中 less版本的 ^ 去掉  重新安装一下 v3.9.0 应该就可以解决问题 大家可以试一下   
虽然 锁定了版本 但是由于 ^, 所以会下载3 一下的最新版本， 最新版本应该是有问题的。

**Comment by lizux** [comment] 2019-08-17 06:36
+1

**Comment by wangmingquan** [comment] 2019-08-17 06:37
+1

**Comment by AlwaysSkylll** [comment] 2019-08-17 06:46
`const shortname = new this.less.FileManager().extractUrlParts(filename).filename;` 

这个类似代码引起的？

**Comment by Tindtily** [comment] 2019-08-17 08:00
omg

**Comment by starzle** [comment] 2019-08-17 08:02
Same here. npm picks up this "minor" release automatically, and breaks all of my builds. :(

**Comment by huxiaoqi567** [comment] 2019-08-17 08:06
+1

**Comment by smackgg** [comment] 2019-08-17 08:33
v3.10.0 same error

**Comment by AlixWang** [comment] 2019-08-17 08:45
+1

**Comment by doxiaodong** [comment] 2019-08-17 08:46
hurry

**Comment by simple7** [comment] 2019-08-17 09:24
+1

**Comment by lixiaohulee** [comment] 2019-08-17 09:52
just use less-loader@5.0.0   every thing will be ok

**Comment by 0x80** [comment] 2019-08-17 12:11
@lixiaohulee 	unless you're not using less-loader and everything will not be ok

**Comment by wangningbo93** [comment] 2019-08-17 12:17
+1

**Comment by asiareal** [comment] 2019-08-17 15:25
+1

**Comment by KatDenisenko** [comment] 2019-08-17 19:40
I have the same problem (((

**Comment by Lalitha-Iyer** [comment] 2019-08-17 19:47
+1

**Comment by kikeztw** [comment] 2019-08-17 23:34
i have the same problem :/

**Comment by matthew-dean** [comment] 2019-08-18 01:44
This is an issue with an older version of `less-loader`, not Less, which did not inherit the Less filemanager correctly. See: https://github.com/less/less.js/issues/3414#issuecomment-522223041

**Comment by lulinglm** [comment] 2019-08-18 02:59
thanks

**Comment by ZhiGang-Fang** [comment] 2019-08-18 07:36
解决了吗?

**Comment by 670755937** [comment] 2019-08-18 08:17
> 解决了吗?

你可以，把你package.js 里的less依赖，重新安装最近小版本依赖。
![image](https://user-images.githubusercontent.com/27992771/63221969-af9be300-c1d3-11e9-80ac-804847abc93e.png)

**Comment by khom-outsourcify** [comment] 2019-08-19 04:55
+1

**Comment by aleen42** [comment] 2019-08-19 06:12
Oooooooooooops!!!

**Comment by montanaflynn** [comment] 2019-08-19 06:27
We're using antd which broke: https://github.com/ant-design/ant-design/issues/18343

How can we fix the issue?

**Comment by aleen42** [comment] 2019-08-19 06:32
@montanaflynn keep a older envrionment and generate locked dependencies map with `npm-shrinkmap.json` may be a good choice.

**Comment by montanaflynn** [comment] 2019-08-19 06:33
@aleen42 thanks, I hope this can be fixed soon, I'm not very familiar with all the npm stuff.

**Comment by aleen42** [comment] 2019-08-19 06:34
@montanaflynn I have met many times when we broke during building due to the unlocked dependencies, including sub dependencies. This is a confusing problems for most FE developers.

**Comment by montanaflynn** [comment] 2019-08-19 06:51
@aleen42 we fixed it by adding 

```
  "devDependencies": {
    "less-loader": "^5.0.0"
  }
```

**Comment by 1312543912** [comment] 2019-08-19 07:18
Why does this problem arise? 
Node.js version is not right?

**Comment by TengSimon** [comment] 2019-08-19 08:13
It's not a node version issue.

**Comment by TengSimon** [comment] 2019-08-19 08:27
1

**Comment by TengSimon** [comment] 2019-08-19 08:28
> Why does this problem arise?
> Node.js version is not right?

+1

**Comment by aleen42** [comment] 2019-08-19 08:30
@montanaflynn you can also fix the problem by specifying a sub version for `less-loader`:

```json
devDepedencies: {
    "less-loader": "4.1.0",
    "less": "3.9.0"
}
```

**Comment by TecHunter** [comment] 2019-08-19 09:24
Upgrade with 
`yarn upgrade less@^3.10.1 less-loader@^5.0.0`

**Comment by gozeon** [comment] 2019-08-19 12:28
use `"less": "~3.9.0"`

**Comment by LizhangX** [comment] 2019-08-19 18:24
+1

**Comment by jenniferneale** [comment] 2019-08-19 19:10
+1

**Comment by matthew-dean** [comment] 2019-08-19 19:17
Incidentally, for those watching this thread, I'll re-open and probably submit a fix later today for older `less-loader` versions, just to have things be less annoying.

It's one of those edge cases where actually using the `Class` syntax to replace a prototype function throws an error without `new`. A FileManager is supposed to always be invoked with `new` (that's the documented API), and older versions of `less-loader` apparently did not.

**Comment by aleen42** [comment] 2019-08-20 00:57
I think that it is better for `less-loader` to downgrade its dependencies below `3.9.0`.

**Comment by matthew-dean** [comment] 2019-08-20 01:33
@aleen42 Why would that be necessary, when the latest version of `less-loader` works fine?

**Comment by aleen42** [comment] 2019-08-20 01:36
Assume that some projects may not need to take care the risk of high level upgrading from `4.x` to `5.x`.

**Comment by LeonWuV** [comment] 2019-08-20 02:32
+666

**Comment by matthew-dean** [comment] 2019-08-20 02:37
Can someone try: https://github.com/less/less.js/pull/3421?

Branch is at: https://github.com/matthew-dean/less.js/tree/release/v3.10.2

The challenge in testing this is that `less-loader`'s own tests fail on 3.9.0, so it's not clear what's expected. But, with Less's exported classes transpiled down to functions, the same errors at least get triggered in `less-loader`, so it's not clear if that's expected output or not. It's also not clear _how_ or why this error occurs in Less loader v4, and doesn't occur in v5, except it may be a Webpack issue on v4?

In any case, if people can confirm that this branch as a Less dependency doesn't cause the class issue, then I'll merge it in.

**Comment by wantwant123** [comment] 2019-08-20 02:52
+1 version less 3.9.0 less-loader 4.1.0

**Comment by MustafinVadim** [comment] 2019-08-20 05:21
+1

**Comment by resyin** [comment] 2019-08-20 06:19
+1

**Comment by lang1427** [comment] 2019-08-20 07:43
Manually specify less version   ：
npm i less@3.9.0 -D     
ok!!!

**Comment by JunlinZhu-Tommy** [comment] 2019-08-20 09:38
Fix by downgrade to 3.9.0

**Comment by vipcxj** [comment] 2019-08-20 10:34
Just before, I delete the node_modules and type `npm i`, this error happen. So the latest version `3.10.1` still has this bug. I choose downgrade to 3.9.0

**Comment by ezgitek** [comment] 2019-08-20 11:02
How would I fix this bug if I am using @zeit/next-less? Any help appreciated.

**Comment by hua1995116** [comment] 2019-08-20 12:03
@ezgitek  
```
npm i @zeit/next-less
npm i less@3.9.0
```

**Comment by buerxixi** [comment] 2019-08-20 15:04
https://forum.vuejs.org/t/vue-cli/72008/7
"less": "^3.10.1",
"less-loader": "^5.0.0",
is running

**Comment by matthew-dean** [comment] 2019-08-20 19:23
> No one with less-loader v4 issues seemed willing to test [3.10.2] 🤷‍♂, but in my testing, Less-loader's v4 tests broke differently with 3.10.1 (class constructor issue), and broke the same with this PR. So..... not sure if it fixes it, but it should be no worse?

I merged that possible fix into master (but not yet released to NPM). Still would love for someone to confirm instead of the +1's.

**Comment by jenniferneale** [comment] 2019-08-20 19:53
I can confirm I just tried the current master branch of less locally with less-loader ^4.1.0, and my project is able to build again. 👍

**Comment by jenniferneale** [comment] 2019-08-20 19:54
Thanks for your work on this!

**Comment by matthew-dean** [comment] 2019-08-20 20:16
@jenniferneale Thanks for confirming! I'll publish to NPM later today then, can't do it from work.

**Comment by pod4g** [comment] 2019-08-21 02:48
+1

**Comment by H4ngman** [comment] 2019-08-23 13:44
Is this issue fixed with 3.10.3?

**Comment by matthew-dean** [comment] 2019-08-25 02:31
@H4ngman Should be. Re-open if not.

**Closed by matthew-dean** 2019-08-25 02:31 UTC
