### ISSUE TITLE
less.tree.functions is undefined 

### ISSUE THREAD

**Issue by MichaelCereda** [less/less.js#2411] opened 2015-01-24 04:34 UTC
I'm trying to access to less.tree.functions from the browser but it says that "functions" is undefined.

the version i'm currently using is 

    <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.2.0/less.min.js"></script>

am i doing something wrong?

**Comment by seven-phases-max** [comment] 2015-01-24 11:02
In v2 `functions` is no longer a part of the `tree` (it's `less.functions` now, also note that this stuff is not supposed to be accessed from anywhere except Less compiler itself. So anything you're going to do with it you'll do at your own risk).

**Comment by SomMeri** [comment] 2015-01-24 12:46
I'm closing this since the issues is not a bug nor feature request.

**Closed by SomMeri** 2015-01-24 12:46 UTC

**Comment by lukeapage** [comment] 2015-01-24 13:35
See
https://github.com/less/less-plugin-advanced-color-functions/blob/master/lib/index.js

For an example on adding a custom function.

**Comment by MichaelCereda** [comment] 2015-01-24 17:13
Ok, thanks for the info.
At this point i'm trying to use less.functions.spin but it's not available...
any chance to reach it?

I'm doing it for an experimental color manipulation tool... so don't worry, i don't need something for production. :)

**Comment by lukeapage** [comment] 2015-01-24 18:54
Following on from the previous example..

https://github.com/less/less.js/blob/master/lib/less/functions/function-registry.js

Function registry has a get function.
