### ISSUE TITLE
Reference importing outputs stuff when it's nested in a selector

### ISSUE THREAD

**Issue by diagramatics** [less/less.js#2762] opened 2015-12-17 03:52 UTC
Not sure if this is intended, but I'm facing this issue right now.

Say if you have a mixin file called `mixins.less`:

```
.a-mixin {
  background: red;
}
```

And you import it as a reference inside a selector:

```
.a-selector {
  @import (reference) "a-mixin.less";
}
```

You'd expect nothing gets outputted, but there is an output:

```
.a-selector {
  .a-mixin {
    background: red;
  }
}
```

**Comment by seven-phases-max** [comment] 2015-12-17 04:28
See #1896.

**Comment by seven-phases-max** [comment] 2015-12-17 04:29
Closing as duplicate of #1896.

**Closed by seven-phases-max** 2015-12-17 04:29 UTC

**Comment by diagramatics** [comment] 2015-12-17 21:08
Ah okay, so the fix hasn't just been released yet?

Thanks for the info!
