### ISSUE TITLE
less 3.x throws an error if there's no return value for a node

### ISSUE THREAD

**Issue by fpsqdb** [less/less.js#3182] opened 2018-02-27 11:18 UTC
After upgrade to 3.0.1 from 2.7.3, less throw an error
" Cannot read property 'length' of undefined" at antd\lib\style\color\bezierEasing.less (line 1, column -1)
it works fine when I down to 2.7.3.

And this is the bezierEasing.less file:

[bezierEasing.less](https://github.com/ant-design/ant-design/blob/9634bea391dd2b7b17f1e89383577e248081a044/components/style/color/bezierEasing.less)

**Comment by seven-phases-max** [comment] 2018-02-27 13:54
See https://github.com/less/less.js/issues/3113.

**Comment by seven-phases-max** [comment] 2018-02-27 13:55
Cosing as duplicate of #/3113.

**Comment by matthew-dean** [comment] 2018-06-05 16:58
Looks like the error has an error.

**Comment by seven-phases-max** [comment] 2018-06-05 19:00
I've fixed the link. It seems they also have already fixed the issue (by adding `return ''` there) though it would be nice to have some feedback.

**Comment by matthew-dean** [comment] 2018-06-06 18:40
It seems there were a few issues that this touched on.

1. not having `javascriptEnabled: true` and using inline JS
2. A bug introduced where the lack of a return statement from, presumably, some node or sub-node of a value property causes an error? Meaning since there wasn't a string returned, it's probably trying to get the length of that string. That one SHOULD be a pretty simple fix. 

While you're reading this, do you have time to review the pile of bug fixes I've made recently?

**Comment by matthew-dean** [comment] 2018-06-25 16:37
Duplicate of #3113.

**Comment by matthew-dean** [comment] 2018-06-25 16:38
Re-opening since this is an issue in the current release, and the previous one was thought to be related to alpha bugs.

**Comment by matthew-dean** [comment] 2018-07-03 15:14
@seven-phases-max 

> I've fixed the link in the first post. It seems they also have already fixed the issue (by adding return '' there) though it would be nice to have some feedback.

Should we fix this? This seems to apply in this case to inline JS, which is deprecated.

**Comment by rjgotten** [comment] 2018-07-03 20:03
> @matthew-dean 
> Should we fix this?

Any custom function or visitor that manipulates the node tree into containing something that evaluates to 'undefined can trigger this situation, I believe.

Some time ago I wrote a few custom functions that did some on the fly AST generation for some hacked together `each` loops that could take a ruleset as a parameter and have an `@item` parameter injected into it (similar to `@arguments`) to hold each item from the looped over list. I ran across the same issue back then due to a missed return statement on a node.

**Comment by matthew-dean** [comment] 2018-07-03 20:32
> Any custom function or visitor that manipulates the node tree into containing something that evaluates particular types of nodes to undefined can trigger this situation, I believe.

Okay, then it's worth checking out. I thought I handled null nodes, but maybe specifically it was for values of `null`.

**Closed** 2018-07-06 06:07 UTC
Labels: bug, needs decision, research needed
