### ISSUE TITLE
3.11.0 version ,gulp-less not work

### ISSUE THREAD

**Issue by bigmeow** [less/less.js#3470] opened 2020-02-10 07:25 UTC
```js
// installed gulp-less last version
require("gulp-less")
```

```
C:\project\com\JK724.XCX.WechatShopping\node_modules\accord\lib\adapter_base.js:105
        throw new Error("'tried to require: " + this.supportedEngines + "'.\nNone found. Make sure one has been installed!");
        ^

Error: 'tried to require: less'.
None found. Make sure one has been installed!
    at Less.Adapter (C:\project\com\JK724.XCX.WechatShopping\node_modules\accord\lib\adapter_base.js:105:15)
    at new Less (C:\project\com\JK724.XCX.WechatShopping\node_modules\accord\lib\adapters\less\2.x - 3.x.js:17:41)
    at Object.exports.load (C:\project\com\JK724.XCX.WechatShopping\node_modules\accord\lib\index.js:31:12)
    at Object.<anonymous> (C:\project\com\JK724.XCX.WechatShopping\node_modules\gulp-less\index.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

in package.json of gulp-less: 
```
    "less": "2.6.x || ^3.7.1",
```

**Comment by Dimitar-Goshev** [comment] 2020-02-10 07:38
We are experiencing the same issue as of today:
`"less": "^3.8.1"`

**Comment by dgavril** [comment] 2020-02-10 07:59
Also reproducible with grunt-contrib-less ("grunt-contrib-less": "2.0.0") which uses "less": "^3.0.4".

**Comment by bigmeow** [comment] 2020-02-10 08:04
My current solution is to lock the `less` version number in the project's package.json file:
```
"less": "3.10.3"
```

**Comment by jmwolfe** [comment] 2020-02-10 19:05
@bigmeow any idea why my CI build is still failing?

I run:

     call npm install --no-optional 

but it doesn't seem to be getting the right version even with package.json above.

**Comment by jmwolfe** [comment] 2020-02-10 21:10
In case any one else has this issue, the problem was I was interpreting someone's comment on the gulp-less project as applying to grunt/bower.. however it was the package.json option for yarn (resolutions:).

This little trick worked for me to peg the dependent less version to 3.10.3:

https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions

only thing is you have to get the right directory in your CI path so it can find npx.  HTH.

**Comment by jmwolfe** [comment] 2020-02-10 21:11
> My current solution is to lock the `less` version number in the project's package.json file:
> 
> ```
> "less": "3.10.3"
> ```

this doesn't seem to work if less is a dependent package to an installed package, like gulp-less.

**Comment by matthew-dean** [comment] 2020-02-10 21:20
Closing as duplicate of https://github.com/less/less.js/issues/3469

**Closed by matthew-dean** 2020-02-10 21:20 UTC
