### ISSUE TITLE
css calc( {percentage} -/+ {pixel amount} ) outputs as calc({percentage - pixel amount as percentage})

### ISSUE THREAD

**Issue by andrew-luhring** [less/less.js#2438] opened 2015-02-05 17:21 UTC
example:

### less:
```less
a {

  left : calc(50% - 40px);
  width: 40px;
}
```

gets compiled as:

### css

```css
a {
  left: calc(50% - 40%);
  width: 40px;

}

/* or */

a {
  left: 10%;
  width: 40px;
}
```

What do?

**Comment by radium-v** [comment] 2015-02-05 17:54
Is Strict Math enabled when you build? http://lesscss.org/usage/#command-line-usage-strict-math

You could try escaping the value:

```less
a {
  left: calc(~"50% - 40px");
  width: 40px;
}
```

**Comment by seven-phases-max** [comment] 2015-02-05 23:50
Yep: [`--strict-math`](http://lesscss.org/usage/#command-line-usage-strict-math).

**Comment by seven-phases-max** [comment] 2015-02-05 23:51
Closing as duplicate of #974.

**Closed by seven-phases-max** 2015-02-05 23:51 UTC
