### ISSUE TITLE
ParseError: Missing closing ')' while creating Not Outputting the Mixin or Parametric mixin

### ISSUE THREAD

**Issue by YahweRaj** [less/less.js#2698] opened 2015-09-19 12:45 UTC
I am trying to create a dynamic mixin name and it throws the error. Refer the below screen shot and code snippet.

@color: #fff;
@a: 2;
.mixin-@{a}(){
  color: @color;
}
div{
  .mixin-2();
}

![image](https://cloud.githubusercontent.com/assets/14360356/9976206/42a1fe96-5efa-11e5-811a-8e0217f6987f.png)

How to resolve this issue? Am I missed something ?

**Comment by seven-phases-max** [comment] 2015-09-20 17:47
No, you can't use variables to form a name of a mixin to invoke. All contexts where variable interpolation is valid are listed in [the docs](http://lesscss.org/features/#variables-feature-variable-interpolation).  

The feature you imagined above is discussed in #1399 among other less or more similar and alternative stuff (in particular there's an opinion that other proposed features would better fit *any* use-cases you could use this one for). 

---
I will close this one as "expected behaviour". Feel free to re-open though, *if* you will invent a use-case for this (a use-case where this feature appears a must have and nothing but this one can resolve it), thus we could treat it as a feature request. But meanwhile, since I know your original use-case was (which is much more easy and more straight-forward to be solved with other stuff), closing...

**Comment by seven-phases-max** [comment] 2015-09-20 17:47
Closing as expected behaviour.

**Closed by seven-phases-max** 2015-09-20 17:47 UTC

**Comment by Bear-Foot** [comment] 2016-08-18 09:34
I'm facing a situation where I need to build a mixin with a variable name.

First, I need to avoid this, and this is why I need it as a silent mixin.
http://stackoverflow.com/questions/31535315/avoiding-output-duplication-using-webpack-less-loader-and-extract-text-webpack

Is there any workaround to to something like `.@{a}()` at the moment ?
