### ISSUE TITLE
when recalled function, the return values is can't be cover.

### ISSUE THREAD

**Issue by kbdsbx** [less/less.js#3052] opened 2017-04-20 06:15 UTC
```less
.test( @a, @b ) {
    @x : @a;
    @y : @b;
}

.test2 {
    .test( 15px, 20px );
    margin: @x @y;

    .test( 20px, 25px );
    margin: @x @y;
}
```

It must be:
```css
.test2 {
    margin: 20px 25px;
}
```
but now it is:
```css
.test2 {
    margin: 15px 20px;
}
```

**Comment by seven-phases-max** [comment] 2017-04-20 06:53
>It must be:

No, the result is actually expected since variables in Less are [lazy-evaluated](http://lesscss.org/features/#variables-feature-lazy-loading) and overridable
(it's actually quite important aspect of the language to understand, for more details see:
- [Lazy-Evaluation](http://lesscss.org/features/#variables-feature-lazy-loading)
- [Variable Semantics](http://earthli.com/news/view_article.php?id=2965) 
- [The World's Most Misunderstood...](http://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/))

For a simple workaround of your example see https://github.com/less/less.js/issues/538#issuecomment-31346194.
For *real* functions use [`less-plugin-functions`](https://github.com/seven-phases-max/less-plugin-functions) (so far at least).

---
Btw., it's also important to realize that mixins and functions are different things. Mixins are *not* functions, they can be used as such to a certain degree, but still different beasts, so in general one is better to avoid using these words  as synonyms as this will be quite misdirecting and confusing (for himself primarily).

**Comment by seven-phases-max** [comment] 2017-04-20 06:57
Closing as expected behaviour (#538, https://github.com/less/less-meta/issues/16).

**Closed** 2017-04-20 06:57 UTC

**Comment by kbdsbx** [comment] 2017-04-20 07:01
Good
