### ISSUE TITLE
[Compile Error] Conflict between less@3.0.0-alpha.3 and antd@2.13.4

### ISSUE THREAD

**Issue by Coodool** [less/less.js#3113] opened 2017-10-10 15:00 UTC
### Version
less@3.0.0-alpha.3
antd@2.13.4

### Steps to reproduce
Compile the antd.less directly in the CLI:
```
lessc ./node_modules/antd/dist/antd.less
```

### Error log
```
FileError: './themes/default' wasn't found. Tried - D:\Projects\ncslab\node_modules\antd\lib\style\themes\default,D:\Projects\ncslab\node_modules\antd\dist\themes\default,D:\Projects\ncslab\node_modules\themes\default,themes\default.less in D:\Projects\ncslab\node_modules\antd\lib\style\index.less on line 1, column 1:
1 @import "./themes/default";
2 @import "./core/index";
```

### Additional comment
It goes well with less@2.7.1.

[Click here for more discussion in ant-design](https://github.com/ant-design/ant-design/issues/7850)

**Comment by matthew-dean** [comment] 2017-10-10 19:06
Thanks for reporting.

**Comment by afc163** [comment] 2017-10-27 02:03
ping~

**Comment by jcgertig** [comment] 2018-02-14 16:45
Needed

**Comment by ram-mar** [comment] 2018-02-23 09:23
Faced the same issue,  occurs in all 3.0.* versions - both in alpha and stable versions.

**Comment by yesmeck** [comment] 2018-02-28 04:04
It seems less 3 does not support the [function hack](https://github.com/ant-design/ant-design/blob/master/components/style/color/bezierEasing.less#L3) anymore, @matthew-dean could you confirm it?

**Comment by yesmeck** [comment] 2018-02-28 07:00
The `FileError: './themes/default' wasn't found` error seems was fixed already. I encounter another error which was reported in #3182.

The reason is the [bezierEasingMixin](https://github.com/ant-design/ant-design/blob/8a6b76acdedbed190ae42b8cf88d233dc9ba6974/components/style/color/bezierEasing.less#L2) function doesn't have a return value, and the parser will try to [parse](https://github.com/less/less.js/blob/b873737f5aa19c7b48f88743cafcf5aa47ac0ed2/lib/less/parser/parser.js#L92) the `undefined` value which leads the error.

**Comment by seven-phases-max** [comment] 2018-02-28 07:04
@yesmeck  This ticket is not for abstract discussions or generic questions (I'll deete both our messages in a few minutes). For your question the answer is: "inine javascript is disabled by default" (see [changelog](https://github.com/less/less.js/blob/master/CHANGELOG.md#300)).

**Comment by yesmeck** [comment] 2018-02-28 07:10
@seven-phases-max Thanks for the response, I'm looking into this issue, and got an error when compile custom function, so I ask the question here.

I found the reason as I commented above, but I don't understand less codebase very well, so I can't figure out how to fix it. Could you take a look?

**Comment by seven-phases-max** [comment] 2018-02-28 07:15
Regarding the "inline javascript" - use [plugins](http://lesscss.org/features/#plugin-atrules-feature) instead.

**Comment by yesmeck** [comment] 2018-02-28 08:40
Thanks!

**Comment by matthew-dean** [comment] 2018-03-02 18:39
> It seems less 3 does not support the function hack anymore, @matthew-dean could you confirm it?

Inline JS was never designed for that purpose, and yes, it's now disabled by default for security reasons. Even without `@plugin` syntax, Less plugins have been around for a long time and have been the intended tool for adding functions. But with `@plugin`, it's even more powerful, because you can isolate your declared functions to Less scope. (Visitors added by `@plugin` are still global.)

**Comment by matthew-dean** [comment] 2018-06-02 17:29
This mainly seems to be an Inline JavaScript / less configuration issue and not a bug.

If the only issue is:

> The reason is the bezierEasingMixin function doesn't have a return value, and the parser will try to parse the undefined value which leads the error.

That may be valid. Leaving open but downgrading this issue.

**Comment by seven-phases-max** [comment] 2018-06-05 09:42
I'm about closing this ticket - because the original issue is solved somehow and for the new one ("`antd` is abusing some inline js hacks" - which is not even a Less issue strictly speaking) it should be a new one. Please, let's not have these "all-in-one" tickets that are impossible to track.

**Comment by matthew-dean** [comment] 2018-06-25 16:37
Closing this alpha bug and moving to #3182.

**Closed by matthew-dean** 2018-06-25 16:37 UTC
Labels: consider closing, needs decision, needs info
