### ISSUE TITLE
When could the extend method use a function as a parameter?

### ISSUE THREAD

**Issue by totoro118** [less/less.js#2554] opened 2015-04-16 07:19 UTC
When could the extend method use a function as a parameter? For example:
.size (@width: 20, @height: 20) {
width: @width;
height: @height;
}
.box {
&:extend(size(50, 50));
}

My Email:963983501@qq.com

**Comment by seven-phases-max** [comment] 2015-04-16 07:29
See #1177.

**Comment by seven-phases-max** [comment] 2015-04-16 07:29
Cosing as duplicate of #1177.

**Closed by seven-phases-max** 2015-04-16 07:29 UTC

**Comment by totoro118** [comment] 2015-04-16 07:45
The syntax is dead, but we are alive, the syntax should be changed with the requirement.

**Comment by seven-phases-max** [comment] 2015-04-16 07:55
@totoro118

I'm not sure what you're talking about with dead/alive but for your specific example see https://github.com/less/less.js/issues/1177#issuecomment-30825680.
