### ISSUE TITLE
css class .clear overwrides mixin .clear()

### ISSUE THREAD

**Issue by wUFr** [less/less.js#2793] opened 2016-01-29 13:12 UTC
Tried to "clear" element with floated elements inside, so content after will stay under it

mixins.less: (inserted before everything else)

```
.clear() {
	display: block; 
	width: 100%; 
	clear: both; 
	content: ""; 
}
```

```
.clear2() {
	display: block; 
	width: 100%; 
	clear: both; 
	content: ""; 
}

```
theme.less:

```
.. some code before
& > .clear {
	&:after {
		.clear();
	}
}
```

```
.ui-tv-navigation {
	border-bottom: 1px solid #e4e3df;

	&:after {
		clear(); <-- this wont work cuz in code before i have classname named .clear; clear2() works
	}
.. some code follows (for items inside)
}
```

**im not sure if its a bug, or "feature" but is it possible to overwrite .mixin() with .mixin{} ? seems pretty strange**

**Comment by seven-phases-max** [comment] 2016-01-29 20:24
Yes, "Feature". By now it's probably to be considered a legacy one that is just impossible to change because the amount of code bases that rely on such behaviour is literally infinite (as the feature is as old as Less itself).

In summary:
Both `.foo;` and `.foo();` calls are considered as identical statements, as well as both `.foo() {...}` and `.foo {...}` definitions are matched by this "the same" call (notice though that mixins (of the same scope) actually [cascade](http://less2css.org/#%7B%22less%22%3A%22%5Cn.foo()%20%7B%5Cn%5Cti-came-from-ruleset%3A%20hello%3B%20%20%5Cn%7D%5Cn%5Cn.foo%20%7B%5Cn%5Cti-came-from-mixin%3A%20hello%3B%20%20%5Cn%7D%5Cn%5Cndiv%20%3E%20%23bar%20%7B%5Cn%20%20%20%20.foo()%3B%5Cn%7D%5Cn%22%7D) not really override).

So yes, as a side-effect we have to carefully choose mixin names. Alternatively you can get use of [namespaces](http://lesscss.org/features/#features-overview-feature-namespaces-and-accessors) to make things a bit more safe, e.g.:
```less
.mylib {
	.foo() {
		color: red;
	}
}

.foo {
	color: blue;
}

div > .bar {
    .mylib.foo();
}
```

**Comment by wUFr** [comment] 2016-02-01 10:34
oky, thanks for explanation! :)

**Comment by seven-phases-max** [comment] 2016-02-01 11:20
Closing as expected behaviour.

**Closed by seven-phases-max** 2016-02-01 11:20 UTC
Labels: Consider Closing, Documentation
