### ISSUE TITLE
@import with url and variable it does not work

### ISSUE THREAD

**Issue by DevAlien** [less/less.js#2873] opened 2016-04-17 21:03 UTC
Hi, I've run into an issue.
basically I want to import fonts like: @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,300,700')

but I would like to put that into a variable but the problem is that the url() will try to find a "css word" inside.
@fontUrl: 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,700';
@import url('@{fontUrl}'); // GIVES AN ERROR
@import url('@{fontUrl}/css'); // WORKS but of course, the url is not what I want.

Example: http://goo.gl/eDdPvM

**Comment by seven-phases-max** [comment] 2016-04-20 22:31
Workaround: [`@import (css) url(@font-url);`](http://less2css.org/#%7B%22less%22%3A%22%40font-url%3A%20'https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans%3A400%2C300%2C700'%3B%5Cn%5Cn%40import%20(css)%20url(%40font-url)%3B%5Cn%20%20%5Cn%22%7D)

**Comment by seven-phases-max** [comment] 2018-02-23 11:34
According to latest discussions this was not a bug actually. An imported "file" *has* to have `.css` extension for the compiler to treat it as a CSS import.
Thus `@import (css) url(@font-url);` is not a workaround but the *proper method* in this case

**Comment by seven-phases-max** [comment] 2018-02-23 11:37
Closing as expected behavior.

**Closed by seven-phases-max** 2018-02-23 11:37 UTC
