### ISSUE TITLE
Error when using css variables without semi.

### ISSUE THREAD

**Issue by honkinglin** [less/less.js#3373] opened 2019-03-12 09:34 UTC
Hey,I found it will parse error when I import a css like this:
`import './test.css'`

```css
// test.css
.test {
    --animate-margin-top: -30px;
    --animate-transform-vertical: top
}
```

the error detail is:

```
ERROR in ./src/test.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    --animate-transform-vertical: top
}

Unrecognised input. Possibly missing opening '{'
......
```

I know it's not a good idea to leave CSS without a semicolon at the end，but  it is normal in the less@2.x version，so it kind of confused me.

**Comment by seven-phases-max** [comment] 2019-03-22 21:44
Confirmed.

**Comment by matthew-dean** [comment] 2020-07-16 18:26
This likely won't be addressed until Less 4.

**Comment by raind33** [comment] 2022-03-03 11:51
Still not good？

**Comment by moelders** [comment] 2022-10-19 11:40
Hello,

The issue is still happening in version `less@3.12.2`.

As @HQ-Lin commented, it happens when you have a variable without semi colon at the end of the block.

This can be fixed by adding the semi colon if you are the owner of the code, but in case of a third-party library it is not viable.

I am using `lessc file.less --clean-css="--s1 --advanced"` to minify some files that later are used in other projects.

**Closed** 2023-01-15 00:55 UTC
Labels: bug, low priority
