### ISSUE TITLE
Double class name in selector

### ISSUE THREAD

**Issue by kirill-konshin** [less/less.js#2589] opened 2015-05-16 08:05 UTC
When LESS version of Twitter Bootstrap is wrapped with a class:

```less
.Bootstrap {
    @import "bower_components/bootstrap/less/bootstrap";
}
```

It produces:

```css
.Bootstrap .Bootstrap .nav:before,
.Bootstrap .Bootstrap .nav:after {
  content: " ";
  display: table;
}
```

All other definitions are correctly wrapped with only one `.Bootstrap` class.

Definition of .nav:

```less
.nav {
  &:extend(.clearfix all);

...

.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}
```

**Comment by seven-phases-max** [comment] 2015-05-16 16:10
See #2052 (and #1850 for more details).

**Comment by seven-phases-max** [comment] 2015-05-16 16:10
Closing as duplicate of #2052.

**Closed by seven-phases-max** 2015-05-16 16:10 UTC
