### ISSUE TITLE
the data-uri does not work?

### ISSUE THREAD

**Issue by nicothin** [less/less.js#2463] opened 2015-02-21 14:35 UTC
`background: data-uri('image/svg+xml;charset=UTF-8', '../img/icons/arr-right.svg');` will be compiled in `background: url("../img/icons/arr-right.svg");`
not inline SVG

**Comment by seven-phases-max** [comment] 2015-02-21 16:46
Any more details n how to reproduce?.

**Comment by nicothin** [comment] 2015-02-22 00:59
grunt project, bug (?) only: https://yadi.sk/d/BtgJ3h_Jepg8s

**Comment by onebitrocket** [comment] 2015-02-22 22:48
I'm getting the same issue in a gulp build running in Yosemite. 

I posted on stackoverflow when I thought. It was gulp, but it's affecting koala output as well. The broken outputted css still looks as mentioned on stackoverflow. 

http://stackoverflow.com/questions/28659431/i-cant-get-the-data-uri-function-to-work-on-gulp-js-to-base64-an-image-on-mac

**Comment by bassjobsen** [comment] 2015-02-23 21:59
from: http://lesscss.org/functions/#misc-functions-data-uri
> data-uri

>Inlines a resource and falls back to url() if the ieCompat option is on and the resource is too large, or if you use the function in the browser.

So try an image smaller 32kb than or run less with the  `--no-ie-compat` option

**Comment by nicothin** [comment] 2015-02-24 07:54
the image has a size of 438b ))

**Comment by lukeapage** [comment] 2015-02-25 06:25
So it doesnt happen with lessc? Can you include the version number of less tested with? if you test with lessc and output to a file you will see warnings - if the file isn't found it also warns and falls back

https://github.com/less/less.js/blob/master/lib/less/functions/data-uri.js#L57

**Comment by koutsenko** [comment] 2015-02-25 17:27
I got the same problem. I've installed less module for npm and used that in my node-based build script. Less script is usual CSS, but with data-uri instead of url. So, LESS works and produces minified (compress: true) code, but without inlined base64 images as I expected... Standalone lessc works like a charm. No debug or error messages present.

**Comment by koutsenko** [comment] 2015-02-25 19:15
I applied a temporary fix in my code.

/build.js
/source/styles.less
/source/res/img1.png
/source/res/img2.png

Paths is styles.less was res/img1.png, I changed them to source/res/img1.png and like so.
It's wrong because paths must be relative to stylesheet file, not the build script.
But it works - inline base64 appears in output.

**Comment by seven-phases-max** [comment] 2015-02-25 20:41
@koutsenko

>Standalone lessc works like a charm. 

Just in case, in your script do you set the `filename` option (e.g. https://github.com/less/less.js/blob/master/bin/lessc#L431) for the `render`? It is a must for relative stuff to work inside compiled Less files.

**Comment by shcarrico** [comment] 2015-03-25 18:04
:+1:  , same issue here.. does not spit any warnings etc either. I am using the grunt-contrib version, but that is pulling less 2.4.0 as stated above

**Comment by seven-phases-max** [comment] 2015-03-25 18:10
Closing due to lack of info (most likely it's a duplicate of #2342, #2524 etc.).

**Comment by seven-phases-max** [comment] 2015-03-25 18:11
Closing due to lack of info (most likely it's a duplicate of #2342, #2524 etc.).

**Comment by nicothin** [comment] 2015-03-25 18:25
if the register address of the image from the root of the project, base64 work and give the correct result.
I wrote earlier reference to a test project, there `less_data_uri_qw\src\less\components\09_breadcrumbs.less`
Set the relative path: `background: data-uri('image/svg+xml;charset=UTF-8', '../img/icons/arr-right.svg');` and it does not work
but if correct, and to do so: `background: data-uri('image/svg+xml;charset=UTF-8', 'src/img/icons/arr-right.svg');` then the image will be converted to base64

**Comment by seven-phases-max** [comment] 2015-03-25 18:26
@ nicothinSo before we re-open that issue could you please answer my Q above?

**Comment by nicothin** [comment] 2015-03-25 19:19
@seven-phases-max 

the answer to your question about how to reproduce the bug:

grunt project: https://yadi.sk/d/BtgJ3h_Jepg8s (`npm i` for test)
less version in grunt-contrib-less — 2.4.0

**Comment by seven-phases-max** [comment] 2015-03-25 20:49
@nicothin Sorry, it seems like I sightly lost in between posts here and misinterpreted a couple of things.

**Comment by bassjobsen** [comment] 2015-03-29 20:57
@nicothin when testing your code i found that you copy your Less files to `temp/less` before compiling them. The Less processor compiles `temp/less/*` which point to your images with `../img`. The `temp` directory does not have the `../img` folder cause that folder only exists in your `src` folder.

I don't think this is a bug, so this issue should be closed.

**Closed** 2015-04-29 12:38 UTC
Labels: Consider Closing
