### ISSUE TITLE
less module resolve algorithm problem

### ISSUE THREAD

**Issue by gogoyqj** [less/less.js#3559] opened 2020-09-30 03:44 UTC
i'm using with bit, project's structure is:

```
boilerplate
├── components/home/sfc-avatar
|  ├── SFCAvatar.less
|  └── node_modules/src/styles/mixins/index.less
└── src/styles/mixins.less
```

and the SFCAvatar.less:

```less
@import 'src/styles/mixins';
```

the less-loader config

```js
{
  test: /\.less$/,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'less-loader',
      options: {
        lessOptions: loaderContext => {
          const { context, rootContext } = loaderContext;
          return {
            paths: [
              path.join(context, 'node_modules'),
              path.join(process.cwd(), 'node_modules'),
              process.cwd()
            ]
          };
        }
      }
    }
  ]
}
```

- Operating System: Mac
- Node Version: 10
- NPM Version: 6.4.1
- webpack Version: 4.28.4
- less-loader Version: 7.0.1
- less Version: 3.12.2

### Expected Behavior

SFCAvatar.less should import the `node_modules/src/styles/mixins/index.less`

### Actual Behavior

 `src/styles/mixins.less` imported

https://github.com/webpack-contrib/less-loader/issues/385#issuecomment-699984385
![image](https://user-images.githubusercontent.com/1776278/94640832-3cd7c380-0312-11eb-9d66-2e266722c762.png)

here is the demo https://github.com/gogoyqj/less-loader-demo

![image](https://user-images.githubusercontent.com/1776278/94422983-7c8b9780-01ba-11eb-919f-ad4cbeceaa5c.png)

**Comment by gogoyqj** [comment] 2020-09-30 05:57
i've tried, if there were both `node_modules/src/styles/mixins/index.less` and ` node_modules/src/styles/mixins/package.json`  then it worked（require.resolve resolved `src/styles/mixins` to `node_modules/src/styles/mixins/index.less`）

**Comment by gogoyqj** [comment] 2020-09-30 08:35
![image](https://user-images.githubusercontent.com/1776278/94662388-e59a1900-033a-11eb-99fb-f6f124490da5.png)

**Comment by matthew-dean** [comment] 2020-11-25 15:12
I'm not sure what this issue means. Yes, Less will look locally, then search paths. Is that not what's happening?

**Comment by gogoyqj** [comment] 2020-11-26 02:52
my mistake. 

this means that Less only try to load from node_modules(using require.resolve) when path[i] is `.`, but paths[i] contains `/node_modules/` will not

https://github.com/less/less.js/blob/0e268598c8327b9e8d36d9bb2edfde95d8d787be/packages/less/src/less-node/file-manager.js#L72
```js
 if (!explicit && paths[i] === '.') {
      try {
          fullFilename = require.resolve(fullFilename);
          isNodeModule = true;
      }
      catch (e) {
          filenamesTried.push(npmPrefix + fullFilename);
          tryWithExtension();
      }
  }
  else {
      tryWithExtension();
  }
```

it works if:

```js
const isNodeModulePath = !!paths[i].match(/[/\\]node_modules[/\\]?/g);

if (!explicit && (paths[i] === '.' || isNodeModulePath)) {
```

**Comment by gogoyqj** [comment] 2020-12-09 03:15
@matthew-dean halo？

**Comment by matthew-dean** [comment] 2020-12-12 02:18
@gogoyqj I guess I still don't really get this. If you're passing in an absolute path, then node.resolve should not be used to try to resolve the path, because, by definition, you HAVE resolved the path in the paths you're passing in. 

So I feel like Less's behavior is correct here.

**Comment by gogoyqj** [comment] 2020-12-14 02:18
@matthew-dean 

an absolute path passed in(with node_modules) should be regarded as a node_module，and paths should be used first then pwd while resolving less modules.

just like sass, if SASS_MODULE is specified "node_modules:src", sass will resolve `node_modules/src/styles/mixins/index.sass` first：

```
boilerplate
├── components/home/sfc-avatar
|  ├── SFCAvatar.sass
|  └── node_modules/src/styles/mixins/index.sass
└── src/styles/mixins.sass
```

while less still resolve 'src/styles/mixins.less' first even paths specified:

```
            paths: [
              path.join(context, 'node_modules'),
              path.join(process.cwd(), 'node_modules'),
              process.cwd()
            ]
```

```
boilerplate
├── components/home/sfc-avatar
|  ├── SFCAvatar.less
|  └── node_modules/src/styles/mixins/index.less
|  └── node_modules/src/styles/mixins/package.json // a package.json and its main property is './index.less'
└── src/styles/mixins.less
```

**Comment by matthew-dean** [comment] 2020-12-14 17:44
@gogoyqj 

> just like sass, if SASS_MODULE is specified "node_modules:src", sass will resolve node_modules/src/styles/mixins/index.sass first

I see, so this is less a "problem", and more of a feature request? The idea is that if `node_modules` is present in any path, then resolve it using Node's resolution?

**Comment by gogoyqj** [comment] 2020-12-15 02:07
@matthew-dean i'm not quite sure this is a "problem" or "feature". if node_modules is present in any path, then resolve it using Node's resolution. less will work more reasonably in my scenario just like sass or npm.

now in my bit based app, i just can only use relative paths instead of alias in less, or less may resolve the "unexpected" less dependencies.

**Comment by rjgotten** [comment] 2021-01-14 15:24
Basically @gogoyqj  is asking that resolutions which go through `paths` pre-empt treating resolutions of `@import` paths that don't have a leading `./`  relative path marker, as if they do.

Basically:
`@import "./src/styles/mixins/index.less` -> always treat as relative to current file
`@import "src/styles/mixins/index.less` -> first try to resolve via `paths` and only if that fails treat as relative to current file

**Comment by matthew-dean** [comment] 2021-11-29 02:58
@rjgotten You mean change the resolution order? 🤔

**Comment by matthew-dean** [comment] 2021-11-29 03:06
@rjgotten That doesn't seem to match this [line / solution](https://github.com/less/less.js/pull/3560/files#diff-db633742e1098ee9754f217b556bffbe55a50184bca195bb9a01177ca3f5c2b7R73), unless I'm mis-reading it. It's specifically testing for a path with the existence of `node_modules` in it.

@gogoyqj says the expected behavior should resolve `@import 'src/styles/mixins'` to `node_modules/src/styles/mixins/index.less`, but that implies `src` is an NPM package? (https://www.npmjs.com/package/src ?) It looks, actually, like src files have actually just been arbitrarily inserted into a _folder_ called node_modules, without being actual node modules, according to the project structure here? https://github.com/less/less.js/issues/3559#issue-711608327

**Comment by matthew-dean** [comment] 2021-11-29 03:16
There's [this line](https://github.com/less/less.js/pull/3560/files#diff-db633742e1098ee9754f217b556bffbe55a50184bca195bb9a01177ca3f5c2b7R75) here with the note: "can't resolve a module without package.json", which, yes that's absolutely correct. Otherwise it's not an NPM module, and we're not going to require.resolve it. I don't see why we should add logic to arbitrarily look in a node_modules folder. If it doesn't contain actual modules; then `node_modules` is just an arbitrary folder name.

Unless, again, I'm misunderstanding, but the original project structure is leading me to believe that. 🤷‍♂️

**Comment by rjgotten** [comment] 2021-11-29 08:24
@matthew-dean 
You're not missing anything. It does break things for other cases again.

The PR you're citing is frankly a very; _very_ bad way of solving this issue.
The crux of the matter is that `node_modules` folders are not meant to be accessed directly as real folders on disk. Period.
Modules residing in such folders should **only** be accessed via the proper node module resolution algorithm.

There are too many edge-cases where preconditioning things on just the folder name will blow up. For instance: what do you do when tooling such as NPM starts de-duping and pulling packages from nested `node_modules` folders upwards in the graph to the top-level `node_modules folder?

So I'd chalk this one up to Bit being stupid and breaking encapsulation by having a module explicitly refer to the nested, i.e. private, dependencies of a sibling module.

**Comment by matthew-dean** [comment] 2021-11-29 19:03
@rjgotten Thanks for confirming, closing. Sorry @gogoyqj, this seems to be out of scope for what Less can fix.

**Closed by matthew-dean** 2021-11-29 19:03 UTC
