### ISSUE TITLE
:extend doesn't work with nested blocks

### ISSUE THREAD

**Issue by tomekwi** [less/less.js#2460] opened 2015-02-19 12:00 UTC
```less
.mother {
  parent: rules;

  .child {
    child: rules;
  }
}

.father {
  &:extend(.mother);
}
```

This outputs:
```css
.mother,
.father {
  parent: rules;
}
.mother .child {
  child: rules;
}
```

I'd rather expect:
```css
.mother,
.father {
  parent: rules;
}
.mother .child,
.father .child {
  child: rules;
}
```

Criticism welcome :)

**Comment by seven-phases-max** [comment] 2015-02-19 12:59
This is expected behaviour (this is just it was implemented initially). For possible `extend` extensions/improvements see #2101.

**Comment by seven-phases-max** [comment] 2015-02-19 12:59
Closing as duplicate of #2101.

**Closed by seven-phases-max** 2015-02-19 12:59 UTC
Labels: Feature Request
