### ISSUE TITLE
Variable calculations inside `calc()` not calculated.

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3221] opened 2018-06-18 22:23 UTC
### Test Case

```less
@a: 10px;
@b: 10px;

.one {
	width: calc(100% - ((@a + @b)));
}
```

### Expected Output (& Output for v2.7.1)

```css
.one {
  width: calc(100% - 20px);
}
```

### Actual Output (lessc v 3.0.4)

(Command: `lessc -sm=on test.less > test.css`)

```css
.one {
  width: calc(100% - 10px + 10px);
}
```

**Comment by matthew-dean** [comment] 2018-06-19 00:04
Closing as duplicate of #3191.

**Closed** 2018-06-20 02:54 UTC
Labels: bug

**Comment by matthew-dean** [comment] 2018-06-20 03:09
So, I slightly misunderstood this, but it's working as expected. Essentially, the calc() bug was recently fixed and no math is performed within `calc()`. But functions within `calc()` will still perform math on their arguments (unless the inner function is also calc.

Meaning, you can hack 2.x behavior with:
```less
.one {
	width: calc(100% - (min(@a + @b)));
}
```
But there's no need, since the calculated result is the same.

**Comment by matthew-dean** [comment] 2018-06-25 23:37
> If so, what's the expectation for this?

The above will/should produce 
```css
.foo {
  width: calc(100% - 20px);
}
```
In other words, variables can be evaluated in `calc()`, but the _resulting expression_ won't be. When you write `width: calc(100% - ((@a + @b)));`, each of `@a` and `@b` will be evaluated, but `10px + 10px` (the result) cannot be, because of the nature of `calc()`. It preserves those expressions.

**Comment by matthew-dean** [comment] 2018-06-25 23:40
@calvinjuarez 
One way to think about this:
```less
@offset: 10px;
width: calc(100vh - (@offset + 10vh));
```
The `px - vh` expression would normally be calculated by Less, but it's value must be untouched, as its true pixel value is only evaluated in browser.

**Comment by calvinjuarez** [comment] 2018-06-26 17:09
Aight, I can dig that.

>The above will/should produce...

Unfortunately that's not what's output at the moment.  I created a new issue for that one (https://github.com/less/less.js/issues/3235).

**Comment by mikejf-pr** [comment] 2018-11-19 02:06
@matthew-dean I'm troubled by the lack of evaluation even for negative variables, as that's not really something that can be properly handled at the moment. If we have a simple 

```
@a: -4px;
div {
	margin-right: calc(0px - @a);
}
```

the resultant output is

```
div {
  margin-right: calc(0px - -4px);
}
```

It would seem to me that LESS should handle signage flips as part of the variable insertion.
