### ISSUE TITLE
Selectors in variables not being parsed

### ISSUE THREAD

**Issue by erquhart** [less/less.js#2499] opened 2015-03-11 13:17 UTC
For example:
```
@pseudo-states: &:hover, &:active, &:focus;

.my-selector {
  @{pseudo-states} {
    // rules
  }
}

// expected output:
.my-selector:hover, .my-selector:active, .my-selector:focus {
  // rules
}

// actual output:
.my-selector &:hover, &:active, &:focus {
  // rules
}
```

Is there a way to get Less to parse the selectors?

Note: I'm aware that I could use a mixin and pass the ruleset in, but that's a workaround, and not a great one at that. Awesome feature, but not the proper tool for this job. One specific limitation of that approach comes when other selectors should be added to a specific instance:

```
// via mixin
.my-selector {
  // can't put additional selectors here
  .pseudo-states({
    // rules
  }, //maybe here as a catch-all arg? feels wrong.);

// via variable
.my-selector {
  .my-other-selector,
  .and-another,
  @{pseudo-states} {
    // rules
  }
}
```

**Comment by seven-phases-max** [comment] 2015-03-11 13:24
See #1421.

**Comment by seven-phases-max** [comment] 2015-03-11 13:24
Closing as duplicate of #1421.

**Closed by seven-phases-max** 2015-03-11 13:24 UTC
