### ISSUE TITLE
Extend hyphen named class name does not work

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [less/less.js#2893] opened 2016-05-05 14:41 UTC
Hey guys,

**Does not** work next:

```
@import (reference) "utils"; // has .u-relative { position: relative; }

.aaa {
  &:extend(.u-relative);
}
```

But works well when there is not hyphen here **u-** like that:

```
@import (reference) "utils"; // has .urelative { position: relative; }

.aaa {
  &:extend(.urelative);
}
```

Expect:
`.aaa { position: relative; }`

Actual:
`.aaa {}` or does not exist at all.

Please extend [this](https://github.com/less/less.js/blob/bcc8ced8b0105c44073a823f441d1fb297697f41/test/less/import-reference-issues/global-scope-import.less) test, or similar with one letter before dash in :extend

P.S. Possibly the same problem as for #1328 [here mentioned.](https://github.com/less/less.js/issues/1328#issuecomment-18547664)

P.P.S. extend of `.uu-relative` works well.

**Comment by seven-phases-max** [comment] 2016-05-05 15:13
I can't reproduce you results with recent Less versions (i.e. 2.5.x-2.6.x).

**Comment by AlexanderTserkovniy** [comment] 2016-05-05 15:31
I have created small project for this:
https://github.com/AlexanderTserkovniy/less-hyphen-extend

**Comment by seven-phases-max** [comment] 2016-05-05 18:34
See #2200.

**Comment by seven-phases-max** [comment] 2016-05-05 18:36
Closing as duplicate of #2200.

**Closed by seven-phases-max** 2016-05-05 18:36 UTC
Labels: NeedsInfo
