### ISSUE TITLE
Fails to parse CSS Selectors Level 4 extensions to :not selectors for compound rulesets

### ISSUE THREAD

**Issue by rjgotten** [less/less.js#3640] opened 2021-08-02 08:28 UTC
Version 4.1.1 - i.e. current as of this writing - and earlier of Less seems to improperly handle parsing of the `:not` pseudo-selector, which causes it throw the error "Missing a closing ')'" when encountering a CSS Selectors Level 4 compound `:not` - e.g.

```css
:not(.foo, .bar) {
}
```

My guess is that the parser component for selector rulesets does a naïve global split based on comma characters into constituent selector rules to process. If this is the case, then it needs to implement a proper front-to-back parse of the whole thing instead, as that would allow it to detect whether the comma occurs within the nested context of a pseudo-selector or not.

**Comment by iChenLei** [comment] 2021-08-02 08:44
same with #3622 , more detail https://github.com/less/less.js/issues/3622#issuecomment-875251159

Less v5 development is working in progress, https://github.com/matthew-dean/less.js/tree/5.x . Matthew (current core maintainer) use [chevrotain](https://github.com/chevrotain/chevrotain) to write new less parser, so he doesn't have much time to fix less 4.x .

**Comment by matthew-dean** [comment] 2021-08-02 15:41
> Less v5 development is working in progress, https://github.com/matthew-dean/less.js/tree/5.x . Matthew (current core maintainer) use chevrotain to write new less parser, so he doesn't have much time to fix less 4.x .

@iChenLei Please don't take the existence of that branch as proof that a Less v5 release will happen (based on that branch). We can discuss on Gitter if you like; it's unrelated to this issue.

We should close this as a dupe of #3622, I think?

**Comment by iChenLei** [comment] 2021-08-02 15:52
Sorry, Sir. My fault.

**Closed by iChenLei** 2021-08-02 15:52 UTC
Labels: feature request
