### ISSUE TITLE
Feature Request: Support lists for selector interpolation

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2544] opened 2015-04-08 00:32 UTC
If I interpolate a list variable in a selector, can you expand it into multiple selectors when nesting?

For example:

**Source**
```less
@tags: a, b, code, dd;

@{tags} {
  &:hover {
   color: red; 
  }
}
```

**Current Output**
```css
a, b, code, dd:hover {
  color: red;
}
```

**Desired Output**
```css
a:hover, b:hover, code:hover, dd:hover {
  color: red;
}
```

**Comment by seven-phases-max** [comment] 2015-04-08 00:59
See #1421 (also #1694 and other issues linked there).

**Comment by seven-phases-max** [comment] 2015-04-08 01:00
Closing as duplicate of #1421.

**Closed by seven-phases-max** 2015-04-08 01:00 UTC
