### ISSUE TITLE
mixin with namespace bring odd things in

### ISSUE THREAD

**Issue by MrRaindrop** [less/less.js#2409] opened 2015-01-23 16:01 UTC
the test less code:
```less
.a.b {
    color: blue;
}

.a {
    .b {
        color: green;
    }
}

.d {
    .a > .b;
}
```

generated css:

```css
.a.b {
  color: blue;
}
.a .b {
  color: green;
}
.d {
  color: blue;  /* this is the odd thing I refered in the title of this issue */
  color: green;
}
```
I suppose this is a bug?.. If not, please point out my misunderstanding（I'm new to less & I'm learning it）

**Comment by seven-phases-max** [comment] 2015-01-23 17:57
See #1205.

**Comment by SomMeri** [comment] 2015-01-24 12:44
I will close this since this is as designed. If you do not have the time to read whole discussion in #1205 read just this [comment](https://github.com/less/less.js/issues/1205#issuecomment-54723879) or the two that follows.

**Closed by SomMeri** 2015-01-24 12:44 UTC

**Comment by totoro118** [comment] 2015-04-16 07:15
When could the extend method use a function as a parameter? For example:
.size (@width: 20, @height: 20) {
        width: @width;
        height: @height;
}
.box {
      &:extend(size(50, 50));
}
