### ISSUE TITLE
Extend

### ISSUE THREAD

**Issue by teratron** [less/less.js#3375] opened 2019-03-15 12:13 UTC
```
@grid: 16;
@e: 2;
.for-media(1);
.for-media(@n, @i: 6, @j: @e) when (@i >= @n) {
    @media only screen and (max-width: (@i*200px + 200px)) {
        @r: @grid - @j;
        .grid {
            grid-template-columns: repeat(@r, minmax(0, 1fr));
        }

        @s: @r + 1;
        .cell-@{s} {
            grid-column: span @r;
        }
        .for-media-cell(@grid);
        .for-media-cell(@m, @k: (@s + 1)) when (@k =< @m) {
            .cell-@{k} {
                &:extend(.cell-@{s}); //**       not work :(       **
                &:extend(.cell-15);   //**       work (for example)       **
            }
            .for-media-cell(@m, (@k + 1));
        }
    }
    .for-media(@n, (@i - 1), (@j + @e));
}
```

**Comment by seven-phases-max** [comment] 2019-03-15 19:16
See #1485.

**Comment by seven-phases-max** [comment] 2019-03-15 19:16
Closing as a duplicate of #1485.

**Closed by seven-phases-max** 2019-03-15 19:16 UTC
