### ISSUE TITLE
Wrapped import and &

### ISSUE THREAD

**Issue by maxvyaznikov** [less/less.js#2555] opened 2015-04-16 14:22 UTC
Create 2 files: issue.less with 
```lesscss
.class-123 {
    background: red;

    textarea& {
        background: blue;
    }
}
```
and issue-wrapper.less with
```lesscss
.wrapper {
    @import "./issue.less";
}
```

Now, compile issue-wrapper: 
```bash
$ node less.js/bin/lessc issue-wrapper.less 
.wrapper .class-123 {
  background: red;
}
textarea.wrapper .class-123 {
  background: blue;
}
```
Expected: 
```lesscss
.wrapper .class-123 {
  background: red;
}
.wrapper textarea.class-123 {
  background: blue;
}
```

**Comment by seven-phases-max** [comment] 2015-04-16 15:23
Current behaviour is expected since (per [Parent Selectors](http://lesscss.org/features/#parent-selectors-feature))

>`& represents all parent selectors (not just the nearest ancestor)

Thus if your ruleset is supposed to be wrapped within another class/namespace you should not use appending `&` there (and search for other solutions).
---

See related feature requests:
#1075
#2256

**Comment by seven-phases-max** [comment] 2015-04-16 15:24
Closing as expected behaviour.

**Closed by seven-phases-max** 2015-04-16 15:24 UTC
