### ISSUE TITLE
::before may shall can contain &.-selectors

### ISSUE THREAD

**Issue by enexusde** [less/less.js#2498] opened 2015-03-11 06:34 UTC
You know ::before is a pseudo-selector.
In Example: 

I use ::before to add a image to a element. But if the element has a css-class of name "selected" a different image-positions should be used:
```css
 .item {
   display:inline-block;
   width: 16px;
   height: 16px;
   content: ''; 
   &::before{
     background: url(foobar.png) -32px 0px;
     &.selected { <-- support missing
       background-position: -16px 0px;
     }
   }
 }
```
This will create this invalid css:
```css
 .item::before.selected {
```
I expected to become
```css
 .item.selected::before {
```

Workaround:
Split the declarations: 
```css
 .item {
   display:inline-block;
   width: 16px;
   height: 16px;
   content: ''; 
   &::before{
     background: url(foobar.png) -32px 0px;
   }
   &.selected::before {
     background-position: -16px 0px;
   }
 }
```

**Comment by bassjobsen** [comment] 2015-03-11 10:28
AFAIK `.item.selected` should do the same as `.selected.item` so you can also use:

```
.item {
   display:inline-block;
   width: 16px;
   height: 16px;
   content: '';
   &::before{
     background: url(foobar.png) -32px 0px;
     .selected& {
       background-position: -16px 0px;
     }
   }
 }
```

outputs:

```
.item {
  display: inline-block;
  width: 16px;
  height: 16px;
  content: '';
}
.item::before {
  background: url(foobar.png) -32px 0px;
}
.selected.item::before {
  background-position: -16px 0px;
}
```

**Comment by seven-phases-max** [comment] 2015-03-11 11:10
See #1942 and #1605.

**Comment by seven-phases-max** [comment] 2015-03-11 11:10
Closing as duplicate of #1942.

**Closed by seven-phases-max** 2015-03-11 11:10 UTC
