### ISSUE TITLE
Implementation in C99 or Lua

### ISSUE THREAD

**Issue by creationix** [less/less.js#2507] opened 2015-03-17 22:31 UTC
I'm trying to use less in my new lua framework but shelling out to node to compile my assets is killing server performance.  Are you aware of any efforts to port less to either C (not C++) or lua?  If not I may try this myself.  It seems much simpler and easier to implement than sass.

Actually for my use, I don't even need the full feature-set.  Simple variables, mixins and nested scope would be enough to make me happy.

**Comment by matthew-dean** [comment] 2015-03-18 00:20
> Are you aware of any efforts to port less to either C (not C++) 

Not without Googling. But improving performance in JavaScript is one of the things we're talking about right now. See: #2501.

And yes, the feature set is smaller than Sass, by design.

**Comment by creationix** [comment] 2015-03-18 03:08
I'm fairly experienced at writing fast parsers in scripting languages (especially in JS for V8).  I'll see if I can find time to write a state-machine parser that doesn't use regular expressions.  Since my immediate need is something that plays well with my lua framework, it will be in lua, but it could help someone wanting to do the same thing in JavaScript, the languages are extremely similar.

Is there a good set of test files I can use for input for supporting less syntax?  Is the formal grammar documented anywhere?

**Comment by matthew-dean** [comment] 2015-03-18 03:35
I don't believe there's a formal grammar. It's kind of like PHP (well, historically), where what the parser does is what should probably happen. There's a lot of documentation though on features on http://lesscss.org/

@seven-phases-max or @lukeapage may be able to give more tips.

**Comment by matthew-dean** [comment] 2015-03-18 03:38
There's also this: https://github.com/mherkender/lua.js

I highly doubt we'd want to convert something from Lua in its entirety that way, but that could help to adapt pieces of work that you've done. Sure you don't want to just write something in JS? ;)

**Comment by matthew-dean** [comment] 2015-03-18 03:39
Oh, and there are tons of .less files to compare to in https://github.com/less/less.js/tree/master/test

**Comment by creationix** [comment] 2015-03-18 04:07
I think I bit off more than I can chew.  The official CSS spec is insane (and very prescriptive).  I assume to be helpful to less, the parser would need no regressions compared to the current one which means parsing all valid CSS at a minimum.  My requirements are much more modest, I just need a subset of CSS and less.

**Comment by matthew-dean** [comment] 2015-03-18 04:36
Yep, there's deceptively a lot in CSS. And even more in Less! ;-)

But if you ever get time to help out with parser, that would be great.

**Comment by creationix** [comment] 2015-03-18 04:44
Sure thing, and thanks for maintaining less.  I'll keep compiling my styles
using node for now.

**Comment by lukeapage** [comment] 2015-03-18 06:26
Any pr that refactors out the regexs to using words and chars (moving
towards tokenising bit by bit) would be accepted - i made a start already
(unreleased).
There is a c# port(dotless), but it is not feature equivalent and uses
regexs like js.

**Comment by SomMeri** [comment] 2015-03-19 08:09
@creationix  You can find even more tests here:
*  [less features](https://github.com/SomMeri/less4j/tree/master/src/test/resources/compile-basic-features)
* [just css](https://github.com/SomMeri/less4j/tree/master/src/test/resources/compile-valid-css)
* [test cases from w3c specification](https://github.com/SomMeri/less4j/tree/master/src/test/resources/w3c-official-test-cases)

Not sure if ANTLR grammar help you, but it is [here](https://github.com/SomMeri/less4j/blob/master/src/main/antlr3/com/github/sommeri/less4j/core/parser/Less.g) is one. Finally, I was describing whatever I ported into less4j on its [wiki](https://github.com/SomMeri/less4j/wiki/Supported-Less-Language) - I tried to put in as much details as I could.

**Comment by rjgotten** [comment] 2015-03-19 13:50
> The official CSS spec is insane (and very prescriptive).

The actual CSS syntax grammar is not *that* complex.
The big things that inflate the parsing logic are error recovery and partial parsing, which Less doesn't do, and detailed rules for certain pseudo-classes and pseudo-elements, which Less isn't interested in.

**Comment by matthew-dean** [comment] 2015-03-19 15:44
Yeah, I was reading through the spec one day, and I came across this:

> When defining a function or a block, the ending token must be specified in the grammar, but if it’s not present in the eventual token stream, it still matches.

So this is supposed to be recovered and interpreted as a complete declaration by a CSS parser:
```
.foo { transform: translate(50px
```
I asked @cloudhead one day about adding some of the same error recovery rules to Less (but not as crazy as above), but he said he liked the fact that the Less parser was also a de facto CSS linter.

**Comment by lukeapage** [comment] 2015-03-19 19:53
closing - a port would be a different repo, performance covered elsewhere

**Closed by lukeapage** 2015-03-19 19:53 UTC
