### ISSUE TITLE
`if` function evaluates both values despite the condition

### ISSUE THREAD

**Issue by thybzi** [less/less.js#3528] opened 2020-07-06 06:11 UTC
Inline conditional function of `if(condition, then-value, else-value)` has some unexpected behavior.

It tries to evaluate "else-value" even if condition is true and else-value in unneeded. In the same way, "then-value" is evaluated even if condition is false.

That may cause 'Operation on an invalid type' error if condition and value processing depends on value type.

```less
.mymixin(@val) {
    myprop: if(isnumber(@val), @val * 42, @val);
}

a {
    .mymixin(11);    // works perfectly with the result of 462
}

b {
    .mymixin(null);  // causes 'Operation on an invalid type' error
}
```

**Comment by matthew-dean** [comment] 2020-07-07 03:39
Duplicate of https://github.com/less/less.js/issues/3371

**Closed by matthew-dean** 2020-07-07 03:39 UTC
