### ISSUE TITLE
@import (reference) and @media

### ISSUE THREAD

**Issue by SebastienDaniel** [less/less.js#2547] opened 2015-04-10 14:31 UTC
Using Grunt-contrib-less (1.0.1)

When importing a .less file containing @media queries, the styles within @media are imported even if the import directive is set to (reference), below is an example:

imported.less
-----------------
```
@someColor: #121311;

h1 {
  color: @someColor;
}

@media (min-width: 600px) {
  h2 {
    color: #000;
  }
}
```

importer.less
----------------
```
@import (reference) "imported.less";
```
will output:
```
@media (min-width: 600px) {
  h2 {
    color: #000;
  }
}
```

**Comment by seven-phases-max** [comment] 2015-04-10 15:02
I can't reproduce this with either Less `2.4.0` or `2.5.0` (`grunt-contrib-less` `1.0.1` and `1.0.0` respectively)... Are you sure this minimal snippet is what that fails? (There're similar `reference` issues (e.g. #1968 + a few more), but the code as above should work fine).

**Comment by SebastienDaniel** [comment] 2015-04-10 15:31
I must admit I didn't test that quick example.

Here is a pastebin link (http://pastebin.com/dStVuRnf) to the file being IMPORTED, which is causing the unexpected output (i.e. the @media content being injected).

As an additional note, contrarily to the suggested duplicates, I'm not using any frameworks or libraries.

**Comment by seven-phases-max** [comment] 2015-04-10 15:42
Then it's #1851 (i.e. it's `&:extend(...)` that causes code to leak through `reference` there).

**Comment by seven-phases-max** [comment] 2015-04-10 15:42
Closing as a duplicate of #1851.

**Closed by seven-phases-max** 2015-04-10 15:42 UTC
Labels: NeedsInfo

**Comment by seven-phases-max** [comment] 2015-04-10 15:55
A suggestion (or a temporary workaround it does not fit well) would be to break that file for (parametric) mixins you're going to use and CSS classes (you're not going to use because of `(reference)`). If you follow that guideline ("never mix reusable parts and final CSS classes") you actually will never need to use `reference` in a Less library.

**Comment by SebastienDaniel** [comment] 2015-04-10 17:09
thx for the reference!
