### ISSUE TITLE
Using :extend with BEM

### ISSUE THREAD

**Issue by dangreen** [less/less.js#2608] opened 2015-06-11 11:45 UTC
This code doesn't work.

```less
.purchase__actions {

	&__cell {
		display: inline-block;
		width: 50%;
		box-sizing: border-box;

		&--full:extend(&) {
			width: 100%;
			padding: 0 15px !important;
		}
	}
}
```

**Comment by seven-phases-max** [comment] 2015-06-15 13:44
See #1554 (as we as #1485 and #2200).

**Comment by seven-phases-max** [comment] 2015-06-15 13:45
Closing as a duplicate of #1554.

**Closed by seven-phases-max** 2015-06-15 13:45 UTC
