### ISSUE TITLE
Conflict between Max of less's built-in function and max of CSS

### ISSUE THREAD

**Issue by bosens-China** [less/less.js#3564] opened 2020-10-19 14:17 UTC
``` css
.minfont(@font) {
    font-size: max(14px, @font)
}
```

What do I need to do to work correctly?

**Comment by matthew-dean** [comment] 2020-12-12 02:46
Duplicate of https://github.com/less/less.js/issues/3463

**Closed by matthew-dean** 2020-12-12 02:46 UTC
