### ISSUE TITLE
Am I crazy, or is it literally impossible to namespace an imported less file?

### ISSUE THREAD

**Issue by GregLancaster71** [less/less.js#2535] opened 2015-04-03 23:48 UTC
I have spent the last several hours reading, and googling how to accomplish this.  My only goal is to @import four files containing mixins.  However, they are borrowed and repurposed from bootstraps grid system so I need them namespaced.  Why is this damn near impossible to do?  

Can someone help me out here?  Even a decent, in depth tutorial link on scoping would be great.  I mean seriously, several hours just trying to import some damn mixins and variables?  I see bootstrap imports mixins without any issue - but they dont use any name spacing.

**Comment by matthew-dean** [comment] 2015-04-03 23:53
You mean as in:
```less
#mynamespace {
  .mixin() {
    foo: bar;
  }
}
.demo {
  #mynamespace.mixin();
}
```
Like that?

**Comment by GregLancaster71** [comment] 2015-04-03 23:56
I tried something almost exactly like that but without the foo: bar:  what
would that be representing?  A variable?   I need to import these four
files, and then call the mixins.

Thanks for the reply too, feel like I'm losing my head here.

**Comment by matthew-dean** [comment] 2015-04-04 00:00
```foo: bar``` is representing a property and value, as in ```color: green```.

**Comment by GregLancaster71** [comment] 2015-04-04 00:04
I am trying to namespace using imports.  Like:

```
#mynamespace {
    @import: 'grid.less';
    @import: 'grid-framework.less';
    @import: 'mixins.less';
    @import: 'variables.less';
}
.demo {
  #mynamespace.make-row();
}
```

Is that something that is possible?

**Comment by seven-phases-max** [comment] 2015-04-04 00:25
You mistake in `:` after `import` - these statements define variables named `import` not really importing files (doh! I guess we should put warning there even if it's absolutely valid Less statement (I saw this typo twcide today :).

**Comment by seven-phases-max** [comment] 2015-04-04 00:29
Either way when you fix this `:` error you stil may face certain problems (assuming these files are from Bootstrap) since Bootstrap uses certain code snippet not compatible with such kind of namespacing (in other words, it is not supposed to be used like this and they officially do not support such code officiausage), for more details on particular problem see:
- https://github.com/less/less.js/issues/2052#issuecomment-45681469
- https://github.com/less/less.js/issues/1709#issuecomment-29707217

**Comment by GregLancaster71** [comment] 2015-04-04 00:39
That was actually a typo.  The code you provided did work, but only for one mixin.  The second returned this upon compiling:
`No matching definition was found for`.

I thought I could namespace it for use like `#mynamespace.make-row();`.  I feel like I'm taking crazy pills!  Maybe i have been looking at the screen to long.  I dont understand why this is difficult.  Literally, all I am trying to do is import the bootstrap `/mixins/grid.less` file and keep it namespaced.

**Comment by seven-phases-max** [comment] 2015-04-04 00:48
Closing this as not an issue (and if it would it's a duplicate of #2052). 
* For "how-to"/"help-me-with" kind of questions the better place to ask is [SO](http://stackoverflow.com/questions/tagged/less).

**Closed by seven-phases-max** 2015-04-04 00:48 UTC
