### ISSUE TITLE
Math Not Evaluated in CSS Custom Properties

### ISSUE THREAD

**Issue by JProffitt71** [less/less.js#3317] opened 2018-10-08 14:46 UTC
I've noticed that variable calculations do not happen inside css var declarations. This came up when I wanted to do this:

```
--gutter: @gutter-width / 2;
```

This got translated into:

```
--gutter: 24px / 2;
```

I know the process of deciding when it should and shouldn't automatically do math is complicated, but is there a way to force it to do that math on a per-property basis? Something like escaping literal strings but for escaping expressions? I'd be fine with using a function like math() or less().

**Comment by rjgotten** [comment] 2018-10-08 22:38
Just adding braces should iirc do the trick.

**Comment by JProffitt71** [comment] 2018-10-09 16:57
Hmm that is not working here.

```
--gutter: (@gutter-width / 2);
```

Produces:

```
--gutter: (24px / 2);
```

If I switch the property to "gutter" (so not a custom property), it works as intended in both cases and does math. E.g.

```
gutter: @gutter-width / 2;
```

Produces:

```
gutter: 12px;
```

**Comment by JProffitt71** [comment] 2018-10-09 17:02
For anyone else that runs into this, a workaround I have found is to use the [Less Functions Plugin](https://www.npmjs.com/package/less-plugin-functions) and create a function that just returns the expression passed to it:

```
.function-expr(@expr) {
    return: (@expr);
}
```

**Comment by matthew-dean** [comment] 2018-10-09 17:54
This is by design. CSS Custom property values are not parsed the same as other values, because they can contain any value whatsoever. Variables are replaced, however.

You can easily work around this by performing math outside the custom property, and assigning to a new variable.
```less
@gutter: 12px;
.custom {
  @gutter-width: @gutter / 2;
  --gutter: @gutter-width;
}
```
Closing as expected behavior.

**Closed by matthew-dean** 2018-10-09 17:54 UTC

**Comment by matthew-dean** [comment] 2018-10-09 18:07
Please open an issue at https://github.com/less/less-docs/ if the documentation is not explicit enough about this.

**Comment by rjgotten** [comment] 2018-10-09 18:07
> This is by design. CSS Custom property values are not parsed the same as other values, because they can contain almost any value whatsoever. 

Ah right; the same exemption as for at-rules, right?

**Comment by matthew-dean** [comment] 2018-10-09 18:21
@rjgotten I believe so, for the same reasons. The Less parser is more permissive for those special rules that contain "anything", but it has obvious trade-offs, such as not allowing inline math.

**Comment by jlixerkun** [comment] 2021-06-04 03:54
you can use calc
` :root {
--gutter-width: 32px;
}
.custom {
--new-gutter-width: calc ( var(--gutter-width) /  2 );
margin: var(--new-gutter-width)
}
`

**Comment by rjgotten** [comment] 2021-06-04 07:42
@jlixerkun 
That trades compile-time math done by the Less compiler for runtime math done by the browser, as well as increasing the size of the compiled CSS. If you're dealing with a compile-time constant, then you should handle it at compile time and leave the runtime calc expressions as simple as possible.
