### ISSUE TITLE
variable @value is undefined when use function each 

### ISSUE THREAD

**Issue by nailfar** [less/less.js#3491] opened 2020-04-16 08:23 UTC
theme_a.less
```
@primary:red;
```
theme_b.less
```
@primary:green;
```
base.less
```
.text-primary{
 color:@primary
}
.bg-primary{
 background-color:@primary
}
```
index.less
```
@themes: a, b;
each(@themes, {
  .theme_@{value} {
    @import "./theme_@{value}.less";
    @import "./base";
  }
});
```
compile failed;
```

@import "./theme_@{theme}.less";
each(@themes, {
^
Error evaluating function `each`: variable @value is undefined
      in /Users/nailfar/Documents/runsa/rs_ips_customer_mp/src/static/less/themeStyle/theme.less (line 4, column 0)
    at runLoaders (/Users/nailfar/Documents/runsa/rs_ips_customer_mp/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/nailfar/Documents/runsa/rs_ips_customer_mp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/nailfar/Documents/runsa/rs_ips_customer_mp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/nailfar/Documents/runsa/rs_ips_customer_mp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
```

**Comment by matthew-dean** [comment] 2020-07-16 15:42
Duplicate of https://github.com/less/less.js/issues/3339

**Closed** 2020-07-16 15:42 UTC
Labels: bug, research needed
