### ISSUE TITLE
Watch-mode for CLI lessc runtime

### ISSUE THREAD

**Issue by tucnak** [less/less.js#2448] opened 2015-02-12 10:09 UTC
Hey there!

Can you please add a watch-mode for CLI runtime? I would love to have smth like `lessc -w` which will watch corresponding input file and rebuild it per change.

Dankeschön!

**Comment by seven-phases-max** [comment] 2015-02-12 13:58
See #1171.

**Comment by seven-phases-max** [comment] 2015-02-12 13:58
Closing as duplicate of #1171.

**Closed by seven-phases-max** 2015-02-12 13:58 UTC
