### ISSUE TITLE
extend requires semicolon

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#2949] opened 2016-08-08 20:04 UTC
This will throw an error:

``` less
.classname { &:extend(.other-classname) }
```

while this will parse/compile fine:

``` less
.classname { &:extend(.other-classname); }
```

**Comment by seven-phases-max** [comment] 2016-09-20 21:32
It does because w/o the semicolon the syntax would be ambiguous:
```less
.classname { &:extend(.other-classname) anotherclassname {...} } 
// ^ is extend on its own there or it's just a part of `& anotherclassname` selector?
```
Note that `extend` here fits the normal CSS selector grammar being the same element as `:not()` or `nth-child()`, so w/o a semicolon it would require ugly hardcoding the parser for the special `extend` cases (that are usually to be avoided if possible).
In simple words the `;` is just shortcut for a missing `{}` block there (either terminating must be there since `&:extend()` is actually ordinal CSS selector (element), i.e. just like `body` for example).

See also somewhat related #2179.

**Comment by seven-phases-max** [comment] 2016-09-20 21:33
Not closing since there might be other opinions but personally I don't see why it can or should be different.

**Comment by seven-phases-max** [comment] 2017-05-23 15:28
Closing as expected behaviour and in favour of #2198 (i.e. there's `extend` syntax inconsistencies but it's a bit wider then just the semicolon itself).

**Closed by seven-phases-max** 2017-05-23 15:28 UTC
Labels: Consider Closing
