### ISSUE TITLE
Error when compiling in Sublime Text 3

### ISSUE THREAD

**Issue by kolik29** [less/less.js#3167] opened 2018-02-14 20:12 UTC
I use Sublime Text 3 with plugin Less2Css and when I save .less  I get error"
`TypeError: pluginLoader.tryLoadPlugin is not a function
    at /usr/lib/node_modules/less/bin/lessc:331:22
    at Array.forEach (<anonymous>)
    at processPluginQueue (/usr/lib/node_modules/less/bin/lessc:330:18)
    at /usr/lib/node_modules/less/bin/lessc:525:9
    at Object.<anonymous> (/usr/lib/node_modules/less/bin/lessc:531:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)`

**Comment by matthew-dean** [comment] 2018-02-14 21:47
Duplicate of #3116

**Closed by matthew-dean** 2018-02-14 21:47 UTC
