### ISSUE TITLE
BUG: Can't override variables with 'when' statement

### ISSUE THREAD

**Issue by jananne** [less/less.js#2634] opened 2015-07-13 11:59 UTC
It's not possible to override @variables with a 'when' statement, like this for example :

@a: false;
@b: 1px;

& when (@a = false) {
@b: 2px;
}

But it is possible it like this:
@a: false;
@b: 1px;

& when (@a = false) {
#c {
width: 2px;
};
}

I tried all kinds of solutions:
http://stackoverflow.com/questions/31378687/less-when-statement-without-classname

Is this a bug?

**Comment by seven-phases-max** [comment] 2015-07-13 13:44
No, not a bug.

`& {}` statement is an ordinal ruleset (just like `div {...}` for example), and as an ordinal ruleset it should not expose its content (variables and mixins) to an outer scope (see #2072 for more details).
There're other ways to achieve conditional variable definition, but to suggest something specific we need you to be a bit more specific example of your use-case. You may also try to search [SO](http://stackoverflow.com/questions/tagged/less) for conditional Less code examples and/or ask about your specific problem there.

**Comment by seven-phases-max** [comment] 2015-07-13 13:46
Closing as expected behaviour (and duplicate of #2072 if it's about to be turned into feature request).

**Closed by seven-phases-max** 2015-07-13 13:46 UTC
