### ISSUE TITLE
3.11 regression: undeclared tslib dependency

### ISSUE THREAD

**Issue by martinpitt** [less/less.js#3476] opened 2020-02-11 06:03 UTC
Starting with 3.11, node_modules/less/dist/less.cjs.js does `require('tslib')`, but less' package.json does not declare this as a dependency.

This now causes project builds to fail like this:
```
ERROR in ./lib/form-layout.less
Module build failed: Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/build/cockpit-project/bots/make-checkout-workdir/cockpit/node_modules/less/dist/less.cjs.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
...
```

**Comment by matthew-dean** [comment] 2020-02-11 06:36
Duplicate of https://github.com/less/less.js/issues/3469

**Closed by matthew-dean** 2020-02-11 06:36 UTC
