### ISSUE TITLE
Variable properties $@ not working within if()

### ISSUE THREAD

**Issue by sabl0r** [less/less.js#3451] opened 2019-11-13 18:35 UTC
Variable properties are working in general but not if you use them within if() (maybe other functions as well).

The code below gives me this for the "nok" mixin:

> property "100" not found 

I know that this feature is not yet documented (https://github.com/less/less-docs/issues/500), but is this usecase supposed to work or not?

```less
@devices: {
	mobile: 420;
	tablet: 800;
	desktop: 1024;
	widescreen: 1280;
	fullhd: 1440;
}


.nok(@d) {
	@w: if(iskeyword(@d), @devices[$@d], @d);
	width: @w;
}

.ok(@d) {
	@w: if(iskeyword(@d), @d, @d);
	width: @w;
}

.ok {
	.ok(tablet);
	.ok(100px);
}

.nok {
	.nok(tablet);
	.nok(100px);
}
```

**Comment by matthew-dean** [comment] 2019-11-13 19:27
This is actually a duplicate of https://github.com/less/less.js/issues/3371

The issue is that all Less functions evaluate all arguments, so you can't optionally evaluate based on the first statement of the function. Therefore the `else` statement immediately fails. This is a planned feature in the future.

**Comment by matthew-dean** [comment] 2019-11-13 19:27
Closing as duplicate.

**Closed by matthew-dean** 2019-11-13 19:27 UTC

**Comment by sabl0r** [comment] 2019-11-14 11:57
Thanks for the fast feedback!
