### ISSUE TITLE
Saturating a gray scale value turns red

### ISSUE THREAD

**Issue by jennevdmeer** [less/less.js#2557] opened 2015-04-19 10:13 UTC
Saturating a gray scale value turns the result red while this should stay gray (unless I'm missing something).

![less example/ photoshop/ expected result](http://i.imgur.com/T891gRJ.png)

## Less used to create example
```less
@size: 10px;
@colors: #333, #666, #ccc, #737d1d, #ad46b5, #2eccdc, #600, #c00, #060;

div {
	border: @size solid black;
	display: inline-block;
	padding: @size;
	margin: @size;
	width: 150px;
	text-align: center;
}

.loop(@i: length(@colors)) when (@i > 0) {
	@color: extract(@colors, @i);

	div:nth-child(@{i}) {
		background-color: @color;
		border-color: saturate(@color, 100);

		color: contrast(@color);
	}
	.loop(@i - 1);
}
.loop;
```

**Comment by seven-phases-max** [comment] 2015-04-19 10:47
Photoshop saturation is relative. Thus to get the same result you need to use `saturate(@color, 100%, relative);`

Red result of absolute saturation, while looks surprising, is actually expected since pure shade of gray colors have undefined hue value and turning an achromatic color into a chromatic one (that's what absolutle saturation makes to grays) also means undefined result (by default the hue value is 0 thus the result is red).

---
Also note that you should not omit `%` for the adjustment parameter (i.e. should be `100%` not `100`), this error is ignored now (i.e. any numeric value is treat as a percentage, despite what [the docs say](http://lesscss.org/functions/#color-operations-saturate)) but in future versions this may be changed. E.g. unitless value will mostlikely becomes a unity ration (i.e. `1` -> `100%`) thus just `100` would be equal to `10000%`.

**Comment by seven-phases-max** [comment] 2015-04-19 10:53
Closing as "expected behaviour".

**Closed by seven-phases-max** 2015-04-19 10:53 UTC
