### ISSUE TITLE
CSS file not generated when using the -M, --depends option

### ISSUE THREAD

**Issue by jdufresne** [less/less.js#2996] opened 2016-11-30 12:47 UTC
This was noticed when upgrading from 2.6 to 2.7.

When using the command such as:

```
$ node_modules/.bin/lessc -M test.less test.css > test.less.d
```

The `test.less.d` is generated correctly, but the file `test.css` will not be generated. If I remove the `-M` option, the `test.css` file is generated correctly. Based on the `--help`, I expect both `test.less.d` and `test.css` to be generated by this command. The dependency file is required for integration with a Makefile. Doing this in one command instead of two improves total build time. 

This worked correctly in 2.6, but not in 2.7.

**Comment by seven-phases-max** [comment] 2016-11-30 15:34
Closing s duplicate of #2925

**Closed by seven-phases-max** 2016-11-30 15:34 UTC
