### ISSUE TITLE
New mixin feature

### ISSUE THREAD

**Issue by mastermehdi** [less/less.js#3029] opened 2017-02-10 20:35 UTC
Can we add a new feature to mixin for supporting this state?

`.test() { color: white; } .test() { color: red; } body { .test() }`

Compiled to:
`a { color: white; color: red; }`

But desired compile is:
`a { color: red; }`

**Comment by seven-phases-max** [comment] 2017-02-11 10:15
We could, but *why* would we? 
(I've already suggested you to start with https://github.com/less/less.js/blob/master/CONTRIBUTING.md. I.e. you propose some feature it's better to have some use-case/rationale behind, beside just "I need that". otherwise the answer is always "No").

From your example it's not even clear if you're looking for a CSS output optimization (i.e. a feature that eliminates "duplicated" properties where necessary - in that case all you need is a descent CSS minifier, e.g. [`clean-css`](https://github.com/jakubpawlowicz/clean-css) with corresponding settings will do it for you). 

*Or* if you're proposing a mixin overriding feature, which is another story, then the further discussion badly needs a concrete use-case example(s).  Start with #1372, #2532 and other related tickets referenced there to collect some background.

**Comment by seven-phases-max** [comment] 2017-02-11 10:21
Not closing yet, but it's either "Not a Less scope (use a minifier)" or a duplicate of #2532.

**Comment by mastermehdi** [comment] 2017-02-12 08:06
When we use 'css minifiers', all of the css files minified! but if we want it just for some parts, we must have a feature to do this!
also we don't want 'mixin overwrite' for some reasons such as compatibilities with all browser!

**Comment by seven-phases-max** [comment] 2017-02-12 08:15
>all of the css files minified! but if we want it just for some parts, we must have a feature to do this!

You can always apply `css-comb` after `css-min`. Yet again, output microoptimization and formatting are out of the Less scope (the compiler just can't afford to burdened by another output analysis layer to do something that's already being done well by other dedicated tools, especially since these tools will always do it better. It's just waste of time and efforts.)

**Comment by seven-phases-max** [comment] 2017-02-12 08:18
Closing as not a Less scope (use [`clean-css`](https://github.com/jakubpawlowicz/clean-css) and [`css-comb`](https://github.com/csscomb/csscomb.js)).

**Closed by seven-phases-max** 2017-02-12 08:18 UTC
Labels: Consider Closing, NeedsInfo
