### ISSUE TITLE
Dividing less render in compile + render

### ISSUE THREAD

**Issue by amolkhatri** [less/less.js#2993] opened 2016-11-23 13:48 UTC
We have a requirement where we want to render less files with different dynamic values based on user selections. The less files are larger it takes around 3sec to generate the CSS. This rendering is happening at runtime. We want to reduce this time. After some analysis we found that generating of AST itself is taking around 500ms. So we want to cache the AST on load time and then render the the CSS based on dynamic values at runtime. For that instead of using render function this is what we are planning to divide in two phases Compile and Render. In compile we will be using less.ParseTree and will cache its output and in Render we will call toCSS on the tree.

This works. But the thing we are worried about if these functions will be supported in future release of less module.

**Comment by seven-phases-max** [comment] 2016-11-23 15:46
It actually was like this before (and still is behind the scenes) - separate `parse` (i.e. generate AST) and `toCSS` (i.e.  AST -> CSS) stages. However the further it goes the more issues pile up simply because even a single variable can turn the whole AST up-side-down (e.g. consider something like `@import "@{some-var}/bla-bla.less";` - some probably never use this feature but others do. So in general it becomes then quite tedious to keep parsing/css-generating thing isolated and independently exposed via API). Well, not sure but it would make sense to search for old issues to find more reasons on replacing `parse/toCSS` pair with `render` in [v2](https://github.com/less/less.js/blob/3.x/CHANGELOG.md#200-b1) (there were some sync/async/promises considerations etc.)
---
As for the ticket itself I wonder if we could treat it as a duplicate of #2640.

**Comment by matthew-dean** [comment] 2016-11-23 18:42
I think the question being asked is, "Will the parse() and render() functions persist with the same signature they have now?" I think the short answer is: yes. There may be other options added, but you can indeed parse and cache the parse tree, and then write your own render function, and that is unlikely to ever change.

**Comment by amolkhatri** [comment] 2016-11-24 09:16
@matthew-dean That answers my question. @seven-phases-max Thank you for the context though.

**Comment by seven-phases-max** [comment] 2017-05-23 16:30
Closing as answered.

**Closed by seven-phases-max** 2017-05-23 16:30 UTC
Labels: Consider Closing, Question
