### ISSUE TITLE
Support file globbing for @imports

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#1181] opened 2013-02-13 16:37 UTC
See: https://github.com/isaacs/node-glob, 
and ~~https://github.com/isaacs/minimatch~~ https://github.com/jonschlinkert/micromatch

I use these often in projects. It would be pretty awesome to be able to do the following and not have to specify individual files:

```
@import "mixins/*.less";
@import "components/**/*.less"; 
``` 

After only a few minutes of using these patterns they become second nature. It might even help with some of the other import issues. 

---

**Comment by BohemMedia** [comment] 2015-01-09 07:35
+1

**Comment by glosee** [comment] 2015-01-15 22:15
As if there aren't enough already: +1

**Comment by AddoSolutions** [comment] 2015-01-22 19:38
+1 seriously

**Comment by steelbrain** [comment] 2015-01-22 19:43
+1

**Comment by tothandras** [comment] 2015-01-22 20:52
:+1:

**Comment by kevnk** [comment] 2015-01-26 18:16
+1

**Comment by dnascimento** [comment] 2015-01-28 15:08
+1

**Comment by maoosi** [comment] 2015-02-09 12:17
+1

**Comment by javoire** [comment] 2015-02-10 12:50
+1

**Comment by simonewebdesign** [comment] 2015-02-10 17:05
:+1: please!

**Comment by davidxd33** [comment] 2015-02-10 23:12
+1 jesus would be happy with wildcard support.

**Comment by matthew-dean** [comment] 2015-02-10 23:42
Hey folks, the feedback is great, but ```+1```s aren't going to make this feature happen any faster. It's marked as ready to be implemented, and when someone implements it, it will be implemented.

> +1 jesus would be happy with wildcard support.

I think it's safe to say that if Jesus were to choose a preprocessor, it would be Less.

**Comment by just-boris** [comment] 2015-02-11 16:11
Because I can't wait resolution of this issue anymore, I write plugin which does it, and use it for my projects. https://github.com/just-boris/less-plugin-glob 
Less allow to create custom file loaders for `@imports`. I've create this one which resolves imports with globs in import path. Any feedback will be appreciated.

**Comment by tonyflp** [comment] 2015-02-12 09:41
@just-boris Hi, I was wondering how I could install this other than by NPM, 

I'm getting the follow errors when using NPM:

npm ERR! 404 'less-glob-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

Thanks in advance, this would save a great deal of heartache.

**Comment by just-boris** [comment] 2015-02-12 09:49
@tonyflp, sorry, there was a typo, you should install `less-plugin-glob`.
Less only accepts plugins named in `less-plugin-*` notation

**Comment by tonyflp** [comment] 2015-02-12 15:30
@just-boris That worked great, thanks for this.

**Comment by equinusocio** [comment] 2015-02-28 12:55
No update for this feature?

**Comment by vospascal** [comment] 2015-03-06 18:32
just-boris i use grunt-contrib-less  they have a example how to load plugin's like this:

plugins: [
        new (require('less-plugin-autoprefix'))({browsers: ["last 2 versions"]}),
        new (require('less-plugin-clean-css'))(cleanCssOptions)
      ],

How would i load your wonderfull plugin in here so that it works with grunt-contrib-less?

**Comment by webfella** [comment] 2015-03-15 22:52
Big :+1: for the feature

**Comment by just-boris** [comment] 2015-03-16 07:21
@vospascal answered in my repo

**Comment by vospascal** [comment] 2015-03-16 08:18
;) thnx @just-boris i saw :-) :+1:

**Comment by srph** [comment] 2015-04-09 22:46
Still waiting for this feature :+1: . Thanks, @just-boris.

**Comment by solovets** [comment] 2015-04-10 10:09
@just-boris thanks! В смысле, спасибо :-)

**Comment by michaelbromley** [comment] 2015-04-15 20:26
This would be a very useful feature for me, since I prefer to bundle all my components in once place, rather than having all Less files in a single location. This leads to Less files existing all over the place, which would be a nightmare to maintain a manual list of imports for.

For anyone using Gulp to build their Less files, I've had success using the gulp-inject plugin to automatically create the `@import` statements in my main Less file. I did a short write-up of it here: http://www.michaelbromley.co.uk/blog/425/automatic-import-of-lesssass-files-with-gulp

**Comment by equinusocio** [comment] 2015-04-15 22:11
For globbing in less simple run in your project 

```npm install less-plugin-glob --save-dev```

then add this to your Gruntfile in the options group of your less task

```plugins: [require('less-plugin-glob')]```

The result is something like this:
```javascript
•••
options: {
	compress: true,
	yuicompress: true,
	optimization: 2,
	cleancss: true,
	sourceMap: false,
	sourceMapFilename: 'css/maps/style.css.map',
	plugins: [require('less-plugin-glob')]
},
•••
```


Now in your .less file you can write this:

```less
•••
@import "commons/**/*";
@import "basic/**/*";
•••
```

**Comment by cody-greene** [comment] 2015-04-18 00:56
Came here wondering if glob imports were supported, but since I'm using a couple of [one-liner shell scripts](https://docs.npmjs.com/misc/scripts) instead of grunt/gulp for my build process. I ended up just using `find` & `cat` and my source stays cleaner than any of the alternatives. Less continues to be awesome.
```sh
# src/index.less + src/foo/bar.less + ... = dist/index.css
find -X src -type f -name '*.less' | xargs cat | lessc - | cleancss --s0 >dist/index.css
```

**Comment by egeste** [comment] 2015-06-02 23:00
+1

**Comment by davidcalhoun** [comment] 2015-06-05 21:43
Really surprised this hasn't happened by now.  Gulp has support for this feature at least.

**Comment by seven-phases-max** [comment] 2015-06-05 21:57
@davidcalhounRead the first post in this thread (I wonder if I should set font size so it goes fulscreen :).

**Comment by AddoSolutions** [comment] 2015-07-10 15:16
Same, as far as I am aware, most people are compiling their LESS files into CSS , I don't know of many sites that are having the browser interpret the LESS directly?

**Comment by SpencerCarstens** [comment] 2015-08-05 18:36
@just-boris I can't get your plugin to work... I assume I'm doing something wrong.

Has anyone else gotten it to work?

Not getting any errors... just no output when I try to use globbing.

```
gulp.task( 'styles', () => {
  return gulp.src( [ 'app/styles/main.less' ] )
    .pipe( $.less( {
      plugins: [ require( 'less-plugin-glob' ) ],
    } ) )
    .pipe( gulp.dest( 'dist/styles' ) );
} );
```
```
// main.less
// Each line below is tried on it's own of course.
@import "app/module/waffle.less"; // Works
@import "app/module/**"; // Does not work.
@import "app/module/**/*"; // Does not work.
@import "app/module/**/*.less"; // Does not work.
```

**Comment by seven-phases-max** [comment] 2015-08-05 18:44
@SpencerCarstens It's better to raise the issue at the plugin own [repository](https://github.com/just-boris/less-plugin-glob/issues).

**Comment by SpencerCarstens** [comment] 2015-08-05 19:40
@seven-phases-max :+1: 

I was hoping to reach a greater audience, but you are right.

**Comment by equinusocio** [comment] 2015-08-06 06:17
@SpencerCarstens You can't integrate the glob-plugin inside less?

**Comment by SpencerCarstens** [comment] 2015-08-06 06:24
It integrates fine, but doesn't seem to do anything.

If I comment out the plugin, my less correctly errors on the import
globing.

When I put it back in, the error stops.

So, I assume it's doing something.

On Wednesday, August 5, 2015, Mattia Astorino <notifications@github.com>
wrote:

> @SpencerCarstens <https://github.com/SpencerCarstens> You can't integrate
> the glob-plugin inside less?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/less/less.js/issues/1181#issuecomment-128262749>.
>


-- 
Cordially,

Spencer Carstens

**Comment by seven-phases-max** [comment] 2015-08-06 07:30
@equinusocio 

>You can't integrate the glob-plugin inside less?

If you mean "why to not put this into the core"... Then, well, the current Less approach (less or more set up in several discussions across various threads here) is roughly: "never put a feature to the core, *before* it becomes absolutely and totally evident the feature belongs there and there's no other ways". That is, if something can be implemented as a plugin it *should* be implemented as a plugin (that's why for example even long-living-in-the-core `clean-css` facility was moved from the core to the corresponding plugin).

**Comment by equinusocio** [comment] 2015-08-06 17:04
@seven-phases-max ok, thanks. I like this.

**Comment by matthew-dean** [comment] 2016-03-04 17:26
Closing as implemented in @just-boris 's plugin.

**Closed by matthew-dean** 2016-03-04 17:26 UTC
Labels: Feature Request, Medium Priority, ReadyForImplementation

**Comment by es6Test** [comment] 2016-04-01 08:39
So we won't support this in browser while in local dev? Can't we make some sort of file crawler?

**Comment by Julyanvdham** [comment] 2017-10-13 09:17
+1

**Comment by satodu** [comment] 2017-11-22 10:20
+1

**Comment by QuantumInformation** [comment] 2017-11-22 10:24
Talk about resurrecting old threads

**Comment by matthew-dean** [comment] 2017-11-22 18:28
What are these +1's supposed to indicate? Is the plugin not workable?

**Comment by Julyanvdham** [comment] 2017-11-23 07:26
The +1 indicates that you want or support it too

**Comment by matthew-dean** [comment] 2017-11-23 18:56
Support what? That's what I'm saying. This has been addressed and the issue is closed. So I'm asking what is being +1'd?

**Comment by davidxd33** [comment] 2017-11-24 03:20
I've been getting these emails for over 2 years what's the deal here..
