### ISSUE TITLE
The browser version of v2.6.0 hides <body> by default

### ISSUE THREAD

**Issue by Justineo** [less/less.js#2812] opened 2016-02-14 06:57 UTC
Online demo: http://jsbin.com/coxinaruri/edit?html,output

Looks like it's introduced in c5283bb.

**Comment by seven-phases-max** [comment] 2016-02-14 07:56
Marking as high-priority since apparently it does not work with default options (i.e. `async = false`).

**Comment by matthew-dean** [comment] 2016-02-14 20:50
It should only hide the body temporarily in "sync" mode, which should probably be the default.

**Comment by matthew-dean** [comment] 2016-02-14 21:09
Okay, I've tracked this down.

The problem is that less.refresh() returns a Promise, and that Promise is not always resolved. The way that it gets resolved is by firing the callback from the loadStyleSheets function. However, the callback is not fired if you _don't have any stylesheets_.

Now, I don't disagree that the body perhaps shouldn't hide on the event of this error, but the plain fact is that you're calling Less.js on a page with no LESS. So it's a user error more than a Less error. So, at the most, this would be a low-priority bug, since in normal usage, it doesn't look like this error would occur.

**Comment by matthew-dean** [comment] 2016-02-14 21:11
Re-marking as low priority unless there's an example of this occurring with LESS styles.

**Comment by seven-phases-max** [comment] 2016-02-14 21:56
>So, at the most, this would be a low-priority bug, since in normal usage, it doesn't look like this error would occur.

It also does not work with [inline only](http://jsbin.com/hifibubiya/edit?html,output) Less styles, i.e. it breaks not only weird incomplete examples.

**Comment by matthew-dean** [comment] 2016-02-14 23:18
@seven-phases-max Ah, okay, bumping back up to high. I'll try to take a look at this soon.

**Comment by Justineo** [comment] 2016-02-15 03:08
@matthew-dean Actually I'm using it in an online Less compiler (http://ecomfe.github.io/est/fiddle/) so it's obviously not a user error to have no Less stylesheets in the page. I'm currently working this around by setting `onReady = false` (which is okay in my use case).

**Comment by seven-phases-max** [comment] 2016-02-15 04:10
> I'm currently working this around by setting `onReady = false` (which is okay in my use case).

A less intrusive workaround would be simply `<script>less = {async: true};</script>`.

**Comment by matthew-dean** [comment] 2016-02-15 04:54
> so it's obviously not a user error to have no Less stylesheets in the page

Yes, my mistake.

**Comment by matthew-dean** [comment] 2016-02-16 01:33
@seven-phases-max So just to be clear, Promises are never fulfilled with inline styles either?

**Comment by seven-phases-max** [comment] 2016-02-16 03:10
>Promises are never fulfilled with inline styles either?

I can't really confirm "never" (since this requires infinite tests :), but from basic tests it appears like so.

**Comment by matthew-dean** [comment] 2017-10-10 05:55
Closing as fixed in #2851.

**Closed by matthew-dean** 2017-10-10 05:55 UTC
Labels: Bug, High Priority
