### ISSUE TITLE
Howto disable HSL color convertion to HEX?

### ISSUE THREAD

**Issue by determin1st** [less/less.js#3176] opened 2018-02-20 21:20 UTC
Hello,

I'm using mostly block functionality of LESS. Is there a way to disable hsl() color translation to hex-value?

**Comment by seven-phases-max** [comment] 2018-02-20 23:24
Closing as not an issue. (Could be a generic feature-request like "preserve original color format when possible" but with very low chances so...).

**Closed by seven-phases-max** 2018-02-20 23:24 UTC

**Comment by determin1st** [comment] 2018-02-21 06:39
okay, will try ~'hsl()', i see two visible problems:

1. color animation to transparent. if i do animate HEX to TRANSPARENT, it goes GRAY at some point, that's not good.

2. dynamic color change through css variable. i dont know how it will work with hex. i could have hsl(var(--hue), var(--satur), 20%) and change hue and satur through JS code.

**Comment by seven-phases-max** [comment] 2018-02-21 11:02
>if i do animate HEX to TRANSPARENT, it goes GRAY

Hmm, `hsl` and `hex` are just different representations of *the same* color value - so if you have your animation working differently for that the same color value,  the problem is not in the color format but elsewhere..

>`hsl(var(--hue), var(--satur), 20%)`

Such statements are not supported in Less yet (see #2986) thus you'll have to use `~""` escaping for such statements. Essentially this problem is not in "Less converting to hex" but in "Less tries to evaluate color functions".
