### ISSUE TITLE
less@3.11.3 seems break less-plugin-functions

### ISSUE THREAD

**Issue by yuxuan** [less/less.js#3579] opened 2020-12-22 10:03 UTC
Use this repo https://github.com/yuxuan/less-plugin-functions-issue to reproduce the issue. I changed less version, and seems [this commit](https://github.com/less/less.js/pull/3532)  broke it. 

I am not sure how to solve this problem, please help.

**Comment by matthew-dean** [comment] 2020-12-27 17:34
I've added your test to Less's main test, and it seems like this issue is caused by however `less-plugin-functions` is patching functions. It could because argument evaluations happen in a different place. That plugin is marked as experimental; but in any case, you'll have to file a bug on that repo.

**Comment by matthew-dean** [comment] 2020-12-27 17:35
@seven-phases-max Do you happen to know how this change affected your plugin?

**Closed by matthew-dean** 2020-12-27 17:34 UTC
Labels: bug, medium priority

**Comment by otakustay** [comment] 2021-03-22 12:28
Seeing the same issue, I've inspected it a little deeper

For less, when `calc(...)` statement is found, it converts this to a `functionCaller` object, inside `functionCaller` it tries to find an implement of corresponding function from `functionRegistry`, for `calc` there is no default built-in implement, so this `functionCaller` is an invalid one.

An invalid `functionCaller` will not be evaluated or replaced, it simple keeps what it is when generating CSS.

The problem is, `less-plugin-functions` is a  deep hack to less's internals, it overrides the `functionRegistry.get` method and always returns a custom implement for any `functionCaller` object. In this case `calc` is considered a real callable function on less's side, so statements like `calc(100vw - 20px)` are not able to preserve its original form, this will become `calc(80vw)`.

`less-plugin-functions` may fix it by adding one more check before it intercepts `functionCaller` objects, however this plugins seems unmaintained currently.
