### ISSUE TITLE
Can't use slashes when importing through variables

### ISSUE THREAD

**Issue by jethrogb** [less/less.js#3209] opened 2018-05-18 18:24 UTC
When using an `@import` statement with a variable, where the variable contains a slash is broken:

```
// main.less
@import url(@brand-include);
```

```
// modules/customer1.less
// (the empty file)
```

```
$ lessc --include-path=modules --global-var=brand-include=customer1.less main.less 
(ok)
$ lessc --include-path=modules --global-var=brand-include=customer1 main.less 
(ok)
$ lessc --global-var=brand-include=modules/customer1.less main.less 
NameError: Recursive variable definition for @brand-include in .../main.less on line 2, column 13:
1 @brand-include: modules/customer1.less;
2 @import url(@brand-include);
3 

$ lessc --global-var=brand-include=modules/customer1 main.less 
FileError: '[object Object],[object Object],[object Object].less' wasn't found. Tried - .../[object Object],[object Object],[object Object].less,.../[object Object],[object Object],[object Object].less,[object Object],[object Object],[object Object].less in .../main.less on line 2, column 1:
1 @brand-include: modules/customer1;
2 @import url(@brand-include);
3 

```

This is all using version 2.7.3

**Comment by seven-phases-max** [comment] 2018-05-18 21:39
First of all: `modules/customer1.less` is not valid variable value (obviously you get a error if you try `@brand-include: modules/customer1.less;`). You'll need quote such values (e.g. --global-var=brand-include="modules/customer1.less") - I don't remember though if such values has to be later explicitly unquoted when used within the code (most likely they haven't).

**Comment by jethrogb** [comment] 2018-05-18 22:00
Ok, it wasn't obvious to me! And the error messages weren't very helpful either. Using the extra quotes works fine.

**Comment by seven-phases-max** [comment] 2018-05-18 23:13
Just in case also consider using `--modify-var` instead, `--global-var` never really made any sense (because of lazy-evaluation).

**Comment by seven-phases-max** [comment] 2018-05-18 23:14
Closing as expected behaviour.

**Closed by seven-phases-max** 2018-05-18 23:14 UTC
