### ISSUE TITLE
Class is undefined if build with empty string.

### ISSUE THREAD

**Issue by Mighty683** [less/less.js#3124] opened 2017-10-23 12:51 UTC
If you build class with empty string for example:
`@variable:  ~'';
.a@{variable}-b {
 a-b: 1
}`
Output will be: `.a-b { a-b: 1 }` and this class can be used.
But if you try use .a-b class in another class as mixin for example:
`.c {
.a-b;
}`
Error 'a-b' is undefined will be present.
`.c {
.a-b;
}` will work only if you declare a-b class this way `.a-b { a-b: 1 }`.

**Comment by matthew-dean** [comment] 2017-10-24 03:17
That's neat but what's the real use case here? Why is an empty string getting injected into a class name like that and why would you ever need it?

**Comment by Mighty683** [comment] 2017-10-27 11:06
I was generating class for different media queries in loop. For example:
className-xs
className-lg
className-md
And wanted to generate non-media overall class named className. It's problem when you want generate classes in loop and one of variants is ~''.

**Comment by seven-phases-max** [comment] 2017-11-06 17:33
This is a duplicate of #2831.

**Comment by seven-phases-max** [comment] 2017-11-06 17:33
Closing as a duplicate of #2831.

**Closed by seven-phases-max** 2017-11-06 17:33 UTC
Labels: Bug, Consider Closing

**Comment by seven-phases-max** [comment] 2017-11-06 17:41
As for the use-case itself (regardless of the bug) - it's the same story as in #2831: *Never* reuse CSS classes as mixins, use real mixins instead (for a detailed description on why this suggestion is so bold see #2702).
