### ISSUE TITLE
Wrong calc compilation

### ISSUE THREAD

**Issue by tompazourek** [less/less.js#2613] opened 2015-06-18 11:32 UTC
When I compile this code (note that it is valid and working CSS):

```CSS
ul.timeline > li > .timeline-panel {
  width: calc(100% - 90px);
  width: -moz-calc(100% - 90px);
  width: -webkit-calc(100% - 90px);
}
```

I get this output:

```CSS
ul.timeline > li > .timeline-panel {
  width: calc(10%);
  width: -moz-calc(10%);
  width: -webkit-calc(10%);
}
```

**Comment by seven-phases-max** [comment] 2015-06-18 12:31
This is expected behaviour if you compile w/o [`--strict-math=on`](http://lesscss.org/usage/#command-line-usage-strict-math). For more details see #974.

**Comment by seven-phases-max** [comment] 2015-06-18 12:32
Closing as expected behaviour (and duplicate of #974).

**Closed by seven-phases-max** 2015-06-18 12:32 UTC

**Comment by tompazourek** [comment] 2015-06-18 15:47
Sorry for the duplicate. Thank you for the answer.
