### ISSUE TITLE
Allow guards to work with undefined variables

### ISSUE THREAD

**Issue by ESchuderer** [less/less.js#1400] opened 2013-07-04 20:17 UTC
```
.guard () when (@variable) {
  a {
    color: red;
  }
}
```

Variable isn't defined, therefore no output.

```
@variable: true;

.guard () when (@variable) {
  a {
    color: red;
  }
}
```

Variable is definied, therefore output:

```
a {
  color: red;
}
```

**Comment by matthew-dean** [comment] 2015-02-04 18:32
Just some clarification for roadmap: This is marked "ReadyForImplementation", but there doesn't seem to be consensus in this thread, and it looks like @seven-phases-max suggested a decent alternative. @lukeapage @seven-phases-max, should ready for implementation be removed?

**Comment by seven-phases-max** [comment] 2015-02-04 20:19
@ matthew-dean Noidea. I suppose here "ReadyForImplementation" is still sort of valid, meaning something like "this feature seems to be not really neseccary but if someone comes up with a PR implementing such thing there will be no resistance" or a sort of :)

**Comment by matthew-dean** [comment] 2015-02-04 20:36
How's that? (Under Consideration)

**Comment by matthew-dean** [comment] 2015-02-04 20:38
To me, "Ready For Implementation" means that there's general (but not necessarily unanimous) consensus that it _should_ be addressed or implemented. I think "Under Consideration" meets your definition.

**Comment by jlukic** [comment] 2015-09-01 21:11
Still running into this issue when using scoping with `& { // do something here }`, would love ability to use `isDefined`

**Comment by seven-phases-max** [comment] 2015-09-01 21:30
While something like `is-defined` make sence, it is not really required. Just *always* define `@foo` (with whatever default value you need), after all if you're using a variable with you styles you *can* predict you need to define it, e.g.:
```less
// in a far far away galaxy of you library default variables:
@foo: whatever;

// the code where you need it
& when not(@foo = whatever) { 
    // @foo is defined by user    
}

// some user code
@foo: bar;
```

**Comment by jlukic** [comment] 2015-09-01 21:57
I'm trying to set up theme previews in the browser. 

This means I have to use `less.js` and overwrite the default `@theme` variable with run-time settings.

Ala
```javascript
window.less.modifyVars({
  theme: 'someOtherValue'
})
```

In my LESS i'm importing a global `theme.less` file that includes
```less
@theme: undefined;

.setTheme {
  @theme : 'default';
}
.setTheme;
```

I've also tried just 
```less
@theme: 'default';
```

In the first case, the outputted value is `undefined` in second case it is always `default`

**Comment by jlukic** [comment] 2015-09-01 22:19
I've narrowed it down to a very specific test case with `@import` causing issues.

In both cases assume:

Javascript
```less
window.less.modifyVars({
  theme: 'changedValue'
});
```
----------------------
In first case both `inner` and `outer` are correctly set to `changedValue`

component
```less
@import 'theme.less';
.inner{
  color: @theme;
}
```

theme.less
```less

@theme: 'default';

.outside {
  value: @theme;
}
```

---------------------------------

In this case outer is set to default and not `changedValue`

component
```less
@import 'theme.less';
.inner{
  color: @theme;
}
```

theme.less
```less

@theme: 'default';
@import "@{theme}"; // theme is set to default not changedValue
```

**Comment by seven-phases-max** [comment] 2015-09-01 23:07
In case of "var in mixin", the snippet turns into:
```
// defaults:
.setTheme {
   @theme: undefined;
}

// custom:
.setTheme {
  @theme: 'default';
}
.setTheme;
```
---
Though for `modifyVars` it should always result `'someOtherValue'` for either snippet you tried (because `modifyVars` works simply by appending plain `@theme: 'someOtherValue';` line right at the end of the compiled source code).  So if `modifyVars` is not working the problem is most likely elsewhere.
I did look at the `button` page code but it's too complex to quickly say what could be possibly wrong. At quick glance I can't see (or maybe just can't understand) how the Less code is recompiled and resulting CSS is reapplied after `modifyVars` (in simple snippets it's done via `less.refreshStyles` following `modifyVars`).  


---
Btw., just in case,  are you sure you're not planning to use `is-default` as something like:
```
.setTheme when (is-defined(@theme)) {
  @theme: 'default';
}
.setTheme;
```
? If so, the problem is that such code will directly violate lazy-evalution principle (`is-defined` should return false if the variable not defined, but since it *will* be defined in that scope immediately so that`is-defined` also has to return true -> unsolvable recursion. (For more details on why conditional imperative-like redefinitions can't safely be allowed in Less see #2072).

**Comment by seven-phases-max** [comment] 2015-09-01 23:24
@jlukic  
>
```less
@theme: 'default';
@import "@{theme}"; // theme is set to default not changedValue
```

Yes, this was one of my suspicions too (Unfortunately I can't test this right now, neither I can guess how this could happen, but yes, it's possible because variable use in imports is real black magic. I'll create a dedicated issue report if this is the problem).

**Comment by jlukic** [comment] 2015-09-01 23:27
I'm fairly certain it has something to do with that wonderful black magic.

I've been working with very simple less files to debug, however I haven't had a chance to create a test-case repo yet. 

In my tests, the failure is specific to using `{@variable}` values in import, but not in css properties.

**Comment by seven-phases-max** [comment] 2015-09-02 15:22
@jlukic I tested it and `modifyVars` works for vars in imports as expected both with `lessc` and with `less.js` (see [codepen demo], it's a bit tricky code there since I need to import from the [gist](https://gist.github.com/seven-phases-max/3c891bc738325a7483a1) scary url, but I suppose it's equal to what your pages are supposed to perform... So it actually seems like the problem is elsewhere).

**Comment by jlukic** [comment] 2015-09-02 16:04
Thanks for taking the time to produce the test case for me. This is pretty clear cut. I'm not sure what's going on for me.. I'll have to investigate

**Comment by ashenden** [comment] 2016-01-03 02:47
Has there been any movement on this request?  I've been anxious for an undefined variable check for some time now.  At the moment, I have a work around that is far from ideal...

```

.text-variant (@element: '') {
  @variant-text-color: "@{element}-text-color";
  & when not (@@variant-text-color = null) {
    color: @@variant-text-color;
  }
}
```

but, for this to work, the variable must exist and be defined as `null` by default.  This would be far more effective/flexible if I could just instead check if the variable even exists in the first place.

**Comment by ivantcholakov** [comment] 2016-10-19 05:09
+1

**Comment by seven-phases-max** [comment] 2017-04-25 10:38
So in summary: implementing an `is-defined` function within a plugin needs less than 15 lines of code. So just do that if you're brave enough.

**Comment by darkguy2008** [comment] 2017-05-20 08:32
+1 to this. Is there any progress on this as a plugin? I mean, @seven-phases-max you know better the code than most contributors, I guess. If it requires around 15 lines of code, why hasn't it been done yet?

**Comment by seven-phases-max** [comment] 2017-05-20 13:29
>If it requires around 15 lines of code, why hasn't it been done yet?

Because nobody is *really* interested? Every feature is cool and "extremely useful" when somebody else does this for you... It gets not so important when you have to spend your own time ;)

>you know better the code than most contributors

This does not mean I have to put anything of my own interest after anything of someone else interest, sorry.

**Comment by seven-phases-max** [comment] 2017-05-20 14:17
To not sound empty, for @ashenden's us-case: here's the proper way to make any of your ruleset to be customizable without the flawed idea of "blind--move-every-CSS-value-to-a-variable-plus-use-something-that-you-dont-use" (I won't get into details why it's actually broken as it's a story for a long blog-post).

There's concept usually named "hooks", so the following "can't make my mind up festival":
```
p {
    & when not (is-defined(@body-text-color)) {
        color: @body-text-color;
    }
    & when not (is-defined(@body-text-color)) {
        background-color: @body-back-color;
    }
}

span {
    & when not (is-defined(@body-text-color)) {
        color: @body-text-color;
    }
    & when not (is-defined(@body-text-color)) {
        background-color: @body-back-color;
    }
}

// .............................................

@body-back-color: blue; // how about gradient?
```
Should be replaced with:
```less
p {
    .body-text();
    .body-back();
    // ^ it's actually better to group all this into a singe entity, e.g. .p()
    // so that as you don't know WHAT or HOW to be customized
    // you don't force any limitations and/or hardcoded approach
    // for something you DID NOT even write
}

span {
    .body-text();
    .body-back();
}

.body-text() {}
.body-back() {}

// .............................................

.body-back() {background-color: blue}
```
Count the lines, count the possibilities, count the limitations.

**Comment by waterplea** [comment] 2017-09-18 10:49
Guys, here's where I ran into this, please take a look at this example and tell me if it's a valid case and cannot be fixed without is-undefined.

I want to load themes in a library like module like that:

In my core app I define variable @theme: 'yellow' and then import library less.

And here's what library less could look like in this case:

@import 'themes/@{theme}';

body {
  background: @primaryColor;
}

This way I could have yellow.less and default.less with @primaryColor: yellow and @primaryColor: red.

In the end, I can write my library using semantic variable names like primaryColor and provide a set of themes with those variables defined. And library user would just define theme name in his app and import library styles.

**Comment by waterplea** [comment] 2017-09-18 11:08
Ok, nevermind, looks like I got it, I just need a importing mixin like this:

`@theme: 'default';

.imports(@theme) when (@theme = 'yellow') {
    @import "themes/yellow";
}
.imports(@theme) when (@theme = 'default') {
    @import "themes/default";
}
.imports(@theme);`

**Comment by seven-phases-max** [comment] 2017-11-06 20:23
@waterplea You can simplify your code to:
```less
@theme: default;

.imports(yellow) {@import "themes/yellow";}
.imports(default) {@import "themes/default";}
.imports(@theme);
```
also note removed redudant quotes.
Though  to be honest I can't see how `@theme: yellow;` (+ all the mixins code) is better then just the explicit `@import "themes/yellow";` line. I.e. first of all are you aware of the [overriding](http://lesscss.org/features/#variables-feature-default-variables)? I.e. you don't need to hide default `@import "themes/default";`, if your library user needs to apply `yellow` stuff - she just imports your yellow theme (yet again it's the same one line) and voilà.

**Comment by waterplea** [comment] 2017-11-07 19:44
I ended up with an optional import of a file that overrides theme or switches to a preset theme. In a project that uses the library we then configure webpack to use alias to that file as a node module if the project needs a different theme. What I wrote before or what you wrote wouldn't work in our case as we are building a UI kit for Angular and it is highly modular. We can import just one button or select control and it has to be aware of the theme we are using with all of its styles encapsulation. The solution is easy to set up so I'm happy with it.

**Comment by seven-phases-max** [comment] 2017-11-07 22:49
>what you wrote wouldn't work in our case as we are building a UI kit for Angular and it is highly modular.
<sub>
What I wrote would work for any level of modularity. I've seen this infinite times before - it's one of the most sad Less understanding problem - people just miss the fundamental Less lazy-loading principle and instead of natural Less overriding construct a heavy file-injecting-based customization  libraries inspired by those from language with directly opposite variable semantics (like PHP, Sass etc.). But never mind, it's normal for a developer to be conservative and keep sticking to a once-tried-and-succeeded design-pattern even if that design-pattern is totally ineffective in a new environment/platform (me is not an exception). It must be something more than just some guy continuously screaming "Guys, you do it wrong!" for this to change :) </sub>

**Comment by waterplea** [comment] 2017-11-08 09:01
I would love to get right, I'm not claiming I understand everything :) Care to explain your suggestion on my example? Here's what we got:

Here's a minimum structural example:

Library:

- import.less
`@import 'theme-default';`
`@import 'mixins';`
- mixins.less
`some mixins here like resetting default browser button styles`
- theme-default.less
`@primary: red;`
`@secondary: blue;`
- theme-secondary.less
`@primary: green;`
`@secondary: yellow;`
- buttonComponent
`@import 'import';`
`.button { color: @primary; }`

Project 1 (default theme):
- component
`@import 'import';`
`body { background: @secondary; }`

Project 2 (secondary theme):
- component
`@import 'import';`
`body { background: @secondary; }`

Our library is added as a node module and within projects we import just the button component from the library. Since it's an Angular module for that button with it's own less file it is compilated separately from the rest of the Project 1 or Project 2.

I've been thinking about this for a while and I couldn't come up with a way to organize less files to allow Project 1 or Project 2 to set what theme file to use when compiling both components and Projects own code. I don't see a way to override styles for button component from within Project's code.

So instead, basically, here's how I wrote import.less:
`@import 'theme-default';`
`@import 'mixins';`
`@import (optional) '~custom-theme';`

And within Projects, if I want to override theme variables for both Projects code and library components I alias this file as module using webpack. This file could have explicit overriding of say @primary or just a switch to secondary theme:
`@import '~myLibrary/styles/theme-secondary';`

So I know about overriding, problem is — user of the library has no way of getting in between "anywhere after your main library file" and the library component code. I get it that what you say would work for frameworks without styles encapsulation, but for Angular it would either not work or I'm misunderstood something in your solution.

**Comment by seven-phases-max** [comment] 2017-11-08 13:55
I see. Then we're actually speaking of the same thing (just in different words). As as soon as  `buttonComponent` (or any other component) is compiled separately, "the project customization master" remains to be the "`import.less`" file and you did exactly what I suggested.  (while "Project 1" and "Project 2" turn to be just another "anything-else" (or "all-in-one"?) components of the same level as `buttonComponent` and not quite a "projects"). 
I.e. this way I'd say you did it right to my taste.

**Comment by ivantcholakov** [comment] 2018-03-08 19:58
@stale Ping.

**Comment by seven-phases-max** [comment] 2018-03-08 20:52
Technically a plugin implementing the feature is available [since 2015](https://github.com/mesosphere/less-is-defined). But personally I never tested it so please don't blame me if something goes wrong (it's just FYI).

**Comment by matthew-dean** [comment] 2018-07-06 21:14
So... I skimmed back through this thread and I can't really determine if this is mostly cases of people mis-understanding Less scope or not.

I don't really see the need to check if vars are defined. Vars should be defined if they're going to be consumed.

```less
@import "library";  // contains @library-color: blue;

@library-color: red;

.box {
  color: @library-color;
}
```
I don't understand the need to conditionally set a property based on the value _changing_.  If the property is set to a variable, just change the variable's value.

That is, if `library.less` has this:
```less
@library-color: blue;
.box {
  color: @library-color;
}
```
All someone would need to do to set its output:
```less
@import "library";
@library-color: red;
```
This would output:
```less
.box {
  color: red;
}
```
Does the OP and others in that thread understand that behavior?

**Comment by calvinjuarez** [comment] 2018-07-07 00:39
I think the use case of "does var exist" is kind of a nice way to do flags.  That is, I don't think there's a conceptually straight-forward "falsey".  Or rather, it's unusual that `true` is the only "truthy" value.  In other words, I think it's a matter of education, rather than a behavior issue.

I think that we could consider closing, since this is usually fixed with one line declaring the default variable value.  Although with Less v3.5 moving toward a more permissive deal, maybe variables inside guards are evaluated more permissively?

My vote is no, though.  `@the-variable: false;` seems to be all most folks need to add.

**Comment by matthew-dean** [comment] 2018-07-07 01:08
Okay closing, thanks @calvinjuarez.

**Closed by matthew-dean** 2018-07-07 01:08 UTC
Labels: feature request, low priority, support as plugin

**Comment by matthew-dean** [comment] 2018-07-07 01:10
What's also happened since this was open is the `if()` function. So you can do `color: if((@variable), green, red);`

**Comment by kbav** [comment] 2018-07-11 12:16
@matthew-dean Thank you so much for writing in with this tip. I saw the addition of if() in the 3.5 release notes, but didn't make the connection to this issue, which I had a unique case for (but not the time for making a reduced version of). Again, very much appreciated. Well done, LESS team.
