### ISSUE TITLE
element selectors cannot be used in mixins

### ISSUE THREAD

**Issue by refractalize** [less/less.js#2690] opened 2015-09-11 12:00 UTC
It seems that element selectors can't be used as mixins:

```less
.mixin input {
  background-color: red;
}

.thing {
  .mixin input;
}
```

Produces:

```
ParseError: Unrecognised input in path/file.less on line 6, column 15:
5 .thing {
6   .mixin input;
7 }
```

Whereas this works perfectly, as you'd expect:

```less
.mixin .input {
  background-color: red;
}

.thing {
  .mixin .input;
}
```

Am I doing it right, or is this broken?

**Comment by seven-phases-max** [comment] 2015-09-11 12:06
[Mixin](http://lesscss.org/features/#mixins-feature):
>You can mix-in class selectors and id selectors...

So it's intended. In general, *non-parametric* mixins do not make too much sense, use [`extend`](http://lesscss.org/features/#extend-feature) instead.

**Comment by seven-phases-max** [comment] 2015-09-11 12:07
Closing as expected behaviour.

**Closed by seven-phases-max** 2015-09-11 12:07 UTC

**Comment by refractalize** [comment] 2015-09-11 12:12
thanks, `extend` worked in my case. But still, _why_ is this behaviour indended? I can't think of a reason why element selectors should be excluded from mixins? Perhaps there's an ambiguity in the syntax?

**Comment by seven-phases-max** [comment] 2015-09-11 13:07
There're multiple reasons. And yes, syntax ambiguity is one of those:

foo {
   bar:baz; // could be both property:value and tag:pseudo-selector
}

**Comment by refractalize** [comment] 2015-09-11 13:09
had to ask, cheers!
