### ISSUE TITLE
Addition dynamic function ("Mixin name interpolation").

### ISSUE THREAD

**Issue by kbdsbx** [less/less.js#3050] opened 2017-04-19 03:40 UTC
Sometimes we should make function in compiling time, like this:

```less
@{prefix}-@{function-name}-@{suffix} () {
};
```

Because we expert the function which don't output to the finial .css file, but it can be used in compiling time. if any function has been output, the finial .css file is so large. ( 400 line come to 20000+ line etc. )

In current occasion, it has been output:

```css
.prefix-function-suffix () {
}
```

**Comment by seven-phases-max** [comment] 2017-04-19 03:48
Please provide more details on *what* you're trying to achieve (instead of *how* you *think* you could do that).
Usually a code like in your example is an XY-problem - similar [to this](https://github.com/less/less.js/issues/2702#issuecomment-144727038) for example (I.e. if you provide your actual use-case I can give a hint on the *proper* way of handling it w/o the dreadful interpolations).

**Comment by kbdsbx** [comment] 2017-04-19 05:29
Sorry for you, English isn't my native language.

This is code fragment:

```less
// library.less
.media-select ( @tag, @value, @min ) when ( @min > 0 ) {
    @{tag} {
        @media ( min-width: @min ) {
            @value();
        }
    }
}
```

first called:

```less
// library.less
.media-select ( 'xs-none', { display : none }, 768px );
```

next:

```less
// project.less
.page {
    .xs-none;
}
```

In the end, It is output:

```css
@media ( min-width: 768px ) {
    .xs-none {
        display: none;
    }
}

@media ( min-width: 768px ) {
    .page {
        display: none;
    }
}
```

I hopes it didn't output ``.xs-none`` in the final project.css, but ``.page`` did.

```css
/* in fantasy */
@media ( min-width: 768px ) {
    .page {
        display: none;
    }
}
```

In current version, the only way to not outputting mixin is append the "()" after the style name like this:

```less
.mixin () {            // It can't be output.
    display: none;
}
.page {
    .mixin;
}
```

But when the style name is variables or include variables, It doesn't work.

```less
// library.less
.media-select ( @tag, @value, @min ) when ( @min > 0 ) {
    @{tag}() {          // error.
        @media ( min-width: @min ) {
            @value();
        }
    }
    ~"@{tag}()" {          // error.
        @media ( min-width: @min ) {
            @value();
        }
    }
    @_tag : @tag + "()"
    @{_tag} {          // error again.
        @media ( min-width: @min ) {
            @value();
        }
    }
}
```

**Comment by seven-phases-max** [comment] 2017-04-19 07:55
Well, this is exactly the case I pointed to above (https://github.com/less/less.js/issues/2702#issuecomment-144727038). In such use-cases you do not encode a hardcoded device ("screen-size") name into a mixin name, but provide it as the mixin parameter simply because it *is* nothing but a mixin parameter.
E.g. this: 
```less
// project.less
.page {
    .xs-none;
}
```
should really be this instead:
```less
// project.less
.page {
    .none(xs);
}
```
Then instead of trying to define *multiple* `@{name}-@{parameter}` mixins by multiple `.media-select` calls, you simply define *the only* `.name(@parameter)` mixin that can handle any arbitrary screen-size.
Yet again see the example in the discussion after https://github.com/less/less.js/issues/2702#issuecomment-144727038 (counting that depending on your coding preferences an exact implementation may vary quite dramatically, e.g. not nessaserry involving any plugins or. See http://stackoverflow.com/questions/41721356 for another example... etc).

**Comment by seven-phases-max** [comment] 2017-04-19 07:58
I'm tending to close this as duplicate of #2702 I will prepare that one according), unless there're any objections.

**Comment by seven-phases-max** [comment] 2017-04-19 08:01
<sub>Honestly I *do* know a hack to get interpolated-mixins-identifiers but I don't think I even should have metioned this at all. But well, [just in case](http://less2css.org/#%7B%22less%22%3A%22%2F%2F%20Note%3A%20every%20time%20you%20use%20such%20code%20a%20kitten%20dies%20somewhere%5Cn%5Cn%40prefix%3A%20bla%3B%5Cn%40name%3A%20%20%20blee%3B%5Cn%40suffix%3A%20bloo%3B%5Cn%5Cn.%40%7Bprefix%7D-%40%7Bname%7D-%40%7Bsuffix%7D%20%7B._()%7B%5Cn%20%20%20%20foo%3A%20bar%3B%5Cn%7D%7D%5Cn%5Cn%5Cn%2F%2F%20usage%3A%5Cn%5Cndiv%20%7B%5Cn%5Ct.bla-blee-bloo._%3B%5Cn%7D%22%7D)).</sub>

**Comment by kbdsbx** [comment] 2017-04-19 10:10
OK, thank you for your response.

The simply way is put the argument into the argument list, but in my less library, the two occasion is existed.

first occasion, the output css label can be use in html class attribute. such as:

```html
<div class="xs-none l-block"></div>
```

second, when I changed the switch, like this:
```less
// @params output
//     true : output all label which can be use in the html class
//     false : just working as a library function.
@ouput : true;
```

All of less call such as ``xs-none`` are only can be calling in other less file, but do not output to the css file.

however, the two occasion is sharing one code.

maybe the one who in you put link is a same idea.

**Comment by seven-phases-max** [comment] 2017-04-19 10:36
>the two occasion is sharing one code.

In general the idea is usually considered flawed for many reasons but primary because that way you create an unnecessary coupling between totally orthogonal stuff (back-end and front-end or in other words the identifiers you use in HTML (your actually CSS styles) and identifiers you use in Less itself reusable components). This usually leads to a maintenance nightmare (in a half of a year they'll ask you to change `xs-none` style and will you remember that this will also affect `.page` and anything else using that? And what if it shouldn't?) 
So it's still preferred to be:
```less
.xs-none {
    .none(xs);
}
.page {
    .none(xs);
}
```
(yes, it's more verbose but it *will* save you hours and days of the debugging headache eventually).

---

Either way for things like:
>All of less call such as xs-none are only can be calling in other less file, but do not output to the css file.

the dedicated solution is [`@import (reference) ...`](http://lesscss.org/features/#import-options-reference)(no need for any true/false variable hackery).

**Comment by matthew-dean** [comment] 2017-04-19 16:59
Yes, close in favor of #2702

**Closed** 2017-04-19 17:16 UTC
Labels: Consider Closing, Feature Request
