### ISSUE TITLE
feature request: calc property

### ISSUE THREAD

**Issue by septs** [less/less.js#2666] opened 2015-08-14 01:31 UTC
```
.selector {
    font-size: 16px;
    line-height: 2;

    height: (font-size * line-height) + border-bottom-height;

    border-bottom: 1px solid #E6E6E6;
}
.selector2 {
   font-size: 12px;

   position: absolute;
   top: -(font-size);
   right: (font-size);
}
```

**Comment by seven-phases-max** [comment] 2015-08-14 07:26
See #2433.

**Comment by seven-phases-max** [comment] 2015-08-14 07:26
Closing as duplicate of #2433.

**Closed by seven-phases-max** 2015-08-14 07:26 UTC
