### ISSUE TITLE
data-url function breaks when upgrading from less@2.1.2 to less 2.0.0 or greater

### ISSUE THREAD

**Issue by onebitrocket** [less/less.js#2469] opened 2015-02-23 17:12 UTC
I was getting an issue in a gulp build environment where my svg icon builder mixing was incorrectly outputting the css styles

```
.image {
    background-image: url('../image.png');
    .svg & {
        background-image: data-uri('image.svg');
    }
}
```

This should output something like
```
 .image{
    background-image: url('../image.png');
  }
  .svg .image {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0iMHB4IiB2aWV3Qm94PSIwIDAgMTAgNDAiID48cmVjdCB5PSIzOSIgZmlsbD0iI0ZGODBDQiIgd2lkdGg9IjUiIGhlaWdodD0iMSIvPjxwYXRoIGZpbGw9IiM4MERERkYiIGQ9Ik01LDM1SDB2LTFoNVYzNXogTTUsMzBIMHYtMWg1VjMweiBNNSwyNUgwdi0xaDVWMjV6IE01LDIwSDB2LTFoNVYyMHogTTUsMTVIMHYtMWg1VjE1eiBNNSwxMEgwVjloNVYxMHogTTUsNUgwVjRoNVY1eiIvPjwvc3ZnPg==);
  }
```

But I'm getting:
```
 .image{
    background-image: url('../image.png');
  }
  .svg .image {
    background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20x%3D%220px%22%20y%3D%220px%22%20width%3D%222px%22%20height%3D%222px%22%20viewBox%3D%220%200%202%202%22%3E%3Crect%20width%3D%222%22%20height%3D%221%22%20%20fill%3D%22%23000000%22%20%2F%3E%3Crect%20y%3D%221%22%20fill%3D%22%233C3C3C%22%20width%3D%222%22%20height%3D%221%22%2F%3E%3C%2Fsvg%3E");
  }
```

Initially, I downgraded gulp-less to gulp-less@1.3.6 and this fixed the issue, I then incrementally upgraded through the gulp-less versions until the css output looked wrong again, and I found that immediately upgrading to gulp-less@1.3.7 caused the issue to appear.

So that fixed the gulp-less issue, but then I checked my old build tool, I used Koala and had it set to use the local/system less compiler and checking the installed version that was less@2.4.0 and I was getting the same data-uri compile issue.

Again I downgraded my local less back to less@1.7.5 and the outputted css complied as expected.
I've then incrementally upgraded thorough the versions of less and tested the compile using koala and found that version less@2.0.0 caused the issue.

Is the change in output an intended feature and I've missed a setting, or a bug?

Thanks

**Comment by bassjobsen** [comment] 2015-02-23 17:44
please see: https://github.com/less/less.js/issues/2454

**Comment by seven-phases-max** [comment] 2015-02-23 17:46
Closing as duplicate of #2454 (expected result since `v2.2.0`).

**Closed by seven-phases-max** 2015-02-23 17:46 UTC

**Comment by onebitrocket** [comment] 2015-02-23 19:05
Thanks for the update.
Is there a reason for the change (performance, browser support)?

**Comment by seven-phases-max** [comment] 2015-02-24 18:32
>Is there a reason for the change (performance, browser support)?

"Gzipped" (this is how modern web stuff usually transfers CSS) variant of uri-encoded svg is smaller in size than base64-encoded one.

**Comment by matthew-dean** [comment] 2015-07-22 05:45
CanIUse.com claims nothing but base64 encoding is supported for SVGs in IE. They're a pretty definitive resource. http://caniuse.com/#feat=datauri

I think the change to uri-encoding is going to continue to cause problems.

**Comment by seven-phases-max** [comment] 2015-07-22 09:32
@matthew-dean In #2184 you'll find that IE (10 and 11) actually does support non-base64 encodings for svgs too (their requirement is just the header to contain encoding, e.g. `data:image/svg+xml;charset=utf-8`). So the info at `caniuse` seems to be just outdated.

**Comment by lukeapage** [comment] 2015-07-22 12:19
No, it does work in IE - see https://github.com/less/less.js/issues/2250#issuecomment-123699736

**Comment by lukeapage** [comment] 2015-07-22 12:31
raised a issue with caniuse - https://github.com/Fyrd/caniuse/issues/1746

**Comment by lukeapage** [comment] 2015-07-22 12:34
p.s. evidence
https://www.browserstack.com/screenshots/1e6e40274b91d9803014b2abb649588ad37642b5

**Comment by matthew-dean** [comment] 2015-07-22 18:48
Oh. Hmmmmmmm....... I wonder where they got that from then.
