### ISSUE TITLE
Variable passing to ruleset by a mixin contain a loop

### ISSUE THREAD

**Issue by oltodo** [less/less.js#2098] opened 2014-07-08 06:05 UTC
Hi,

This is my parametric mixin contain a loop who set a @width variable and provide to ruleset :

```less
.foo (@ruleset) {
    .loop(1);

    .loop (@index) when (@index < 4) {
        @width: 30px * @index;

        .bar {
            @ruleset();
        }

        .loop(@index + 1);
    }
}
```

When I call this mixin twice like that :

```less
.foo({
    width: @width;
});
.foo({
    width: @width;
});
```

I have this output :

```less
.bar {
  width: 30px;
}
.bar {
  width: 60px;
}
.bar {
  width: 90px;
}

.bar {
  width: 30px;
}
.bar {
  width: 30px;
}
.bar {
  width: 30px;
}
```

The first three are correct but the last three stay on `30px` width.

Strangely, the following example has no problem :

```less
.first {
    .foo({
        width: @width;
    });
}

.second {
    .foo({
        width: @width;
    });
}
```

An idea ?
Thanks.

**Comment by SomMeri** [comment] 2015-10-02 13:14
I think that this is not really a bug, the scopes here are working as designed. Since variables are returned, first call introduces `@width` into the global scope. Detached ruleset then uses `@width` as defined in his own (global) scope.

Maybe we should close this?

**Comment by seven-phases-max** [comment] 2015-10-02 15:43
Closing as expected behaviour.

**Closed by seven-phases-max** 2015-10-02 15:43 UTC
Labels: Bug, Consider Closing, Medium Priority
