### ISSUE TITLE
Time units are stripped when value is 0

### ISSUE THREAD

**Issue by herrethan** [less/less.js#2686] opened 2015-09-09 13:08 UTC
I'm using Less 1.7.5.

Writing `animation-delay: 0s, 1s;` properly outputs this: `animation-delay: 0s, 1s`.

However this:
```
@my-duration: 1s;
animation-delay: 0s, @my-duration;
```

improperly outputs:
```
animation-delay:0,1s
```

It seems the `s` or `ms` unit is stripped from time values when the value is 0, and when it is on the same line as a referenced less variable. 0 without a unit is a invalid syntax for any CSS animation duration.

**Comment by seven-phases-max** [comment] 2015-09-09 16:08
Don't use `-x` option, it's deprecated since v2.2.0. Use `--clean-css` instead.

**Comment by seven-phases-max** [comment] 2015-09-09 16:08
Closing as not applicable to current Less versions.

**Closed by seven-phases-max** 2015-09-09 16:08 UTC

**Comment by lukeapage** [comment] 2015-09-09 16:12
we also fixed this in 1.5.0.. I just started trying to reproduce..  we do have a regression test for it,  so it may be your minifier and not less?

**Comment by seven-phases-max** [comment] 2015-09-09 17:02
Hmm, indeed, I did not think it's actually still working properly in `2.5.1` (`s` is not removed by `-x`), can't say for `1.7.5`.
