### ISSUE TITLE
Conditional not stripped when used with media query in mixin

### ISSUE THREAD

**Issue by atmarx** [less/less.js#2073] opened 2014-06-26 23:26 UTC
I'm using a mixin to allow me to easily apply some rulesets to a class.  The less code is:

    @small: ~"only screen";
    @medium: ~"only screen and (min-width: 40.063em)";
    @large: ~"only screen and (min-width: 64.063em)";
    @xlarge: ~"only screen and (min-width:90.063em)";
    @xxlarge: ~"only screen and (min-width:120.063em)";

    .sizes(@srules: 0; @mrules: 0; @lrules: 0; @xlrules: 0; @xxlrules: 0) {
    	@media @small { @srules(); }
    	@media @medium when not (isnumber(@mrules)) { @mrules(); }
    	@media @large when not (isnumber(@lrules)) { @lrules(); }
    	@media @xlarge when not (isnumber(@xlrules)) { @xlrules(); }
    	@media @xxlarge when not (isnumber(@xxlrules)) { @xxlrules(); }
    }

However, when a rule calling this mixin is parsed using less 1.7.3, the resulting class ends up looking like:

    @media only screen {
      #content nav .top {
        max-width: 1em;
      }
    }
    @media only screen and (min-width: 40.063em) when not (false) {
      #content nav .top {
        max-width: 3em;
      }
    }
    @media only screen and (min-width: 64.063em) when not (false) {
      #content nav .top {
        max-width: 4em;
      }
    }
    @media only screen and (min-width:90.063em) when not (false) {
      #content nav .top {
        max-width: 1em;
      }
    }

Should 'when not (false)' be stripped by the parser?

**Comment by seven-phases-max** [comment] 2016-01-15 00:40
Looking at the issue example once more I realize now it's actually an expected behaviour. The trick is that `when not` part of the `@media ... when not (something) {}` statement is considered to be just some regular ("unknown") identifier(s) like `all`, `screen` or `whatever` (and `(something)` then just becomes a media feature part) hence the resulting CSS. It should not cause any error because the statement is valid CSS (even if it makes no particular sense either to Less or to browsers).

**Comment by seven-phases-max** [comment] 2016-01-15 00:41
Closing as expected behaviour.

**Closed by seven-phases-max** 2016-01-15 00:41 UTC
Labels: Low Priority, NeedsDecision
