### ISSUE TITLE
Support @return in mixin

### ISSUE THREAD

**Issue by rentalhost** [less/less.js#2667] opened 2015-08-14 01:39 UTC
Currently we can use a king of hack to return a value from a mixin. For instance:

```less
.sum (@a, @b) { 
    @return: (@a + @b); 
}
.size { 
    .sum(5px, 10px); 
    width: @return; 
    .sum(15px, 15px); 
    height: @return; 
}
```

But it is ugly.

Suggestion is use the `@return` variable to literally return a value directly from mixin.

```less
.size {
    width: .sum(5px, 10px);
    height: .sum(15px, 15px);
}
```

Both should return:

```css
.size {
    width: 15px;
    height: 30px;
}
```

To avoid breaking changes, both examples should work. `@return` will keep to set the variable on scope, but too will be used as result of mixin.

**Comment by seven-phases-max** [comment] 2015-08-14 07:24
See #538 and [less-plugin-functions](https://github.com/seven-phases-max/less-plugin-functions).

**Comment by seven-phases-max** [comment] 2015-08-14 07:25
Closing as duplicate of #538.

**Closed by seven-phases-max** 2015-08-14 07:25 UTC
