### ISSUE TITLE
JS API does not expose warnings/errors - tooling can't make use of these/display them

### ISSUE THREAD

**Issue by cnweibo** [less/less.js#2753] opened 2015-12-05 17:04 UTC
Hi, I have posted a thread in stackoverflow about gulp-less. I want to know how to deliver error information when an error happens during extend a non-existing mixing/class.
http://stackoverflow.com/questions/34107876/is-there-any-way-to-let-gulp-less-print-error-in-case-extend-a-non-existing-mixi

Can you have a look and give me clue. Following is copied from stackoverflow:

In my less build process, i use the gulp-less. In the build process, i use gulp-plumber to print out error information during that build. It works well for the less syntax error, reference to non-exist variables. Unfortunately, the gulp-less build task print out nothing in case we extend a non-existing mixin/class. Does anyone know about how to enable such kind of "error" or even warning during the build? Following is the gulpfile:
```
gulp.task('less',function(){
var pagelessentry = config.pagelessentry;
log(pagelessentry);
return gulp
.src(pagelessentry)
.pipe(plumber({
errorhandler: errorhandler
}))
.pipe(debug({
title: 'LESS'
}))
.pipe(sourcemaps.init())
.pipe(less())
.pipe(uncss({
html: ['index.html', 'http://homestead.app'],
ignore: [/header-down/,/header-up/]
}))
.pipe(sourcemaps.write(projectrootdir+'public/preparebuild/assets/css/',{includeContent: true}))
.pipe(gulp.dest(projectrootdir+'public/preparebuild/assets/css/'));
});
```
Following is the "wrong" less code where i want gulp to print out some "error or warning" information:
```
.footer{
background-color: @primary-background;
&:extend(.NONEXISTING all);
}
```
In above code, when we extend .NOEXISTING mixin, nothing printed out.
It is quite annoying thing.
Please help me out
Thanks~!

**Comment by SomMeri** [comment] 2015-12-05 21:08
Please use [backtics for format your code](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), it will be easier to read and github wont sent email to whoever has the same username as your variables. I added backticks to your comment.

I do not use gulp-less, but you might have more luck to ask question/feature request in [gulp-less repository](https://github.com/plus3network/gulp-less).

I am closing the issue since it is neither bug or feature request (it is possible to continue discussion and answer questions in closed issues too).

**Comment by cnweibo** [comment] 2015-12-06 01:57
@SomMeri ,
Thanks for your reply.
I have asked gulp-less guys, they are not sure whether or not it is a less issue itself.
Can you confirm whether or not it is a less bug, otherwise , anything missing in the configuration will cause that "bug"?
Thanks~!

**Comment by cnweibo** [comment] 2015-12-06 05:33
@SomMeri ,
I have asked gulp-less guys, they said it should be the less compiler's issue.
"
This seems like an issue where less is not reporting errors back via the JS API. You should open an issue with less so they can add this in.
"
Please refer to: 
https://github.com/plus3network/gulp-less/issues/206#issuecomment-162270040

Can you re-open this or refer it to other issue for tracking this??

Thanks~!

**Comment by contra** [comment] 2015-12-06 05:53
Yes, this is a less issue - warnings are unavailable when using the JS API so no tooling can make use of these.

**Comment by SomMeri** [comment] 2015-12-06 07:41
I changed title from "gulp-less print out nothing error in case extend a non-existing mixin" to "JS API does not expose warnings/errors - tooling can't make use of these/display them" so it is immediately clear from issues list what the issue is about.

**Comment by seven-phases-max** [comment] 2015-12-06 09:41
> "JS API does not expose warnings/errors - tooling can't make use of these/display them" 

This is simply untrue. [Demo](https://github.com/less/less.js/blob/v2.5.3/bin/lessc#L440-L455) - it's JS, it's API, it's exposed (it's a bit akward to use, at least to my personal taste, but it *is* there).

**Comment by SomMeri** [comment] 2015-12-08 07:55
@contra Is the API shown in previous comment good for you and we can close this issue? Is it missing something you need (what)?

**Comment by contra** [comment] 2015-12-08 22:27
@SomMeri Yeah that looks fine, we need to get accord to add it now

**Comment by matthew-dean** [comment] 2015-12-08 23:06
> it's a bit akward to use, at least to my personal taste, but it is there

Shall we start a less-api repo? Not to document what is (although in part), but to maybe have a goal for what to design towards?

**Comment by SomMeri** [comment] 2015-12-09 07:58
@matthew-dean You mean something like unified example about how the api should be used?

**Closed** 2015-12-09 07:59 UTC
Labels: Consider Closing
