### ISSUE TITLE
Interpolated selectors list with nested selectors

### ISSUE THREAD

**Issue by pribilinskiy** [less/less.js#2626] opened 2015-07-07 10:40 UTC
*Source:*
```
@c: .a, .b;

@{c} {
  &,
  & p {
    prop: value;
  }
}
```

Should be the same as if we would write:
```
.a, .b {
  &,
  & p {
    prop: value;
  }
}
```

But...

*Compiled:*
```
.a, .b,
.a, .b p {
  prop: value;
}
```

*Expected:*
```
.a,
.b,
.a p,
.b p {
  prop: value;
}
```

**Comment by seven-phases-max** [comment] 2015-07-07 13:33
See #1421.

**Comment by seven-phases-max** [comment] 2015-07-07 13:34
Closing as duplicate of #1421.

**Closed by seven-phases-max** 2015-07-07 13:34 UTC
